### ISSUE TITLE
sql大写BEGIN会报错

### ISSUE THREAD

**Issue by wangzihaogithub** [MyCATApache/Mycat2#326]
21:15:06 T=Thread-1 [io.mycat.proxy.session.Session setLastMessage at 122]-[ERROR] 
com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'BEGIN', expect END, actual null, pos 5, line 1, column 6, token EOF
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:430)
	at com.alibaba.fastsql.sql.parser.SQLParser.accept(SQLParser.java:438)
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseBlock(MySqlStatementParser.java:2228)
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseStatementListDialect(MySqlStatementParser.java:1600)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:551)
	at io.mycat.commands.MycatdbCommand.parse(MycatdbCommand.java:223)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:145)
	at io.mycat.commands.MycatdbCommand.run(MycatdbCommand.java:97)
	at io.mycat.client.UserSpace.execute(UserSpace.java:134)
	at io.mycat.client.UserSpace.execute(UserSpace.java:81)
	at io.mycat.DefaultCommandHandler.handleQuery(DefaultCommandHandler.java:69)
	at io.mycat.command.ThreadModeCommandDispatcher.lambda$handleQuery$0(ThreadModeCommandDispatcher.java:26)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:119)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:111)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:138)
	at io.mycat.runtime.MycatDataContextImpl.run(MycatDataContextImpl.java:270)
	at io.mycat.command.ThreadModeCommandHanlderImpl.run(ThreadModeCommandHanlderImpl.java:17)
	at io.mycat.command.ThreadModeCommandDispatcher.handleQuery(ThreadModeCommandDispatcher.java:26)
	at io.mycat.command.CommandResolver.handle(CommandResolver.java:69)
	at io.mycat.proxy.handler.MycatHandler.onSocketRead(MycatHandler.java:57)
	at io.mycat.proxy.handler.MycatHandler.onSocketRead(MycatHandler.java:36)
	at io.mycat.proxy.reactor.ProxyReactorThread.processReadKey(ProxyReactorThread.java:151)
	at io.mycat.proxy.reactor.ProxyReactorThread.run(ProxyReactorThread.java:208)

**Comment by wangzihaogithub** [comment]
字段long 转date报错

00:10:44 T=noBindingExecutor9 [com.atomikos.util.DynamicProxySupport logDebug at 32]-[DEBUG] atomikosJdbcStatementProxy for vendor instance com.mysql.cj.jdbc.StatementWrapper@1d5a3bd3: calling proxied close
00:10:44 T=noBindingExecutor9 [io.mycat.proxy.session.Session setLastMessage at 122]-[ERROR] 
java.lang.ClassCastException: java.lang.Long cannot be cast to java.sql.Date
	at io.mycat.api.collector.AbstractObjectRowIterator.getDate(AbstractObjectRowIterator.java:114)
	at io.mycat.resultset.TextResultSetResponse.getValue(TextResultSetResponse.java:152)
	at io.mycat.resultset.TextResultSetResponse.access$000(TextResultSetResponse.java:31)
	at io.mycat.resultset.TextResultSetResponse$1.next(TextResultSetResponse.java:55)
	at io.mycat.resultset.TextResultSetResponse$1.next(TextResultSetResponse.java:44)
	at io.mycat.SQLExecuterWriter.writeToMycatSession(SQLExecuterWriter.java:80)
	at io.mycat.SQLExecuterWriter.writeToMycatSession(SQLExecuterWriter.java:57)
	at io.mycat.ReceiverImpl.sendResponse(ReceiverImpl.java:196)
	at io.mycat.ReceiverImpl.sendResultSet(ReceiverImpl.java:187)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.lambda$onSelectTable$3(SelectSQLHandler.java:224)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThreadPool.lambda$run$3(BindThreadPool.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
00:10:44 T=noBindingExecutor9 [com.atomikos.util.DynamicProxySupport close at 112]-[DEBUG] atomikosJdbcConnectionProxy (state = sessionHandleState (1 context(s), isTerminated = false) for resource defaultDs2) for vendor instance com.mysql.cj.jdbc.ConnectionWrapper@50dd1701: calling native toString
00:10:44 T=noBindingExecutor9 [io.mycat.datasource.jdbc.datasource.DefaultConnection close at 112]-[DEBUG] close com.mysql.cj.jdbc.ConnectionWrapper@50dd1701
00:10:44 T=noBindingExecutor9 [com.atomikos.util.DynamicProxySupport logDebug at 32]-[DEBUG] atomikosJdbcConnectionProxy (state = sessionHandleState (1 context(s), isTerminated = false) for resource defaultDs2) for vendor instance com.mysql.cj.jdbc.ConnectionWrapper@50dd1701: calling proxied close

**Comment by wangzihaogithub** [comment]
fix 

https://github.com/MyCATApache/Mycat2/pull/327
