### ISSUE TITLE
请问：Druid  数据源连接mycat2.0出错

### ISSUE THREAD

**Issue by superBinLiu** [MyCATApache/Mycat2#330]
1.  com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://0.0.0.0:8066/db1?useUnicode=true&serverTimezone=UTC, errorCode 1105, state HY000
     2.  java.sql.SQLException:  HY000 java.lang.IllegalArgumentException: No enum constant io.mycat.beans.mysql.MySQLVariablesEnum.performance_schema
![image](https://user-images.githubusercontent.com/62001174/84253181-34c8fd80-ab42-11ea-83ac-9e80c7e96e2d.png)

**Comment by junwen12221** [comment]
可以报告一下所用的jdbc驱动

**Comment by junwen12221** [comment]
已修复

**Comment by superBinLiu** [comment]
可以连上cat2.0了，但是spingboot+mybaties 在查询sql的时候出错：
客户端错误日志：
![image](https://user-images.githubusercontent.com/62001174/84341515-e6fdd500-abd5-11ea-96bb-bed8c9ff7b64.png)
![image](https://user-images.githubusercontent.com/62001174/84344159-99d13180-abdc-11ea-85c9-8b5ced3ec7d3.png)

mycat2.0 服务端日志：
![image](https://user-images.githubusercontent.com/62001174/84341473-c46bbc00-abd5-11ea-804b-d2190fc7488c.png)此处为null

**Comment by junwen12221** [comment]
往前应该还有一个错误

**Comment by junwen12221** [comment]
io/mycat/calcite/CalciteRunners.java:51 在此处应该有一个错误

**Comment by superBinLiu** [comment]
您好，mycat2.0 服务端开启xa，客户端insert 事务正常，但是查询出现异常；
mycat2.0 服务端不开启xa，客户端insert异常，但是查询正常；
insert 和 select 不兼容

**Comment by junwen12221** [comment]
insert异常是什么报错吗

**Comment by superBinLiu** [comment]
![image](https://user-images.githubusercontent.com/62001174/84480857-cada6080-acc7-11ea-9918-83981374129a.png)
 nested exception is java.sql.SQLException:  HY000 java.lang.IllegalArgumentException
	at io.mycat.ReceiverImpl.lambda$execute$8(ReceiverImpl.java:342)
	at io.mycat.ReceiverImpl.lambda$block$12(ReceiverImpl.java:444)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThread.processJob(BindThread.java:92)
	at io.mycat.bindThread.BindThread.run(BindThread.java:52)
	at io.mycat.bindThread.BindThreadPool.runOnBinding(BindThreadPool.java:176)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:126)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:111)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:138)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.block(ServerTransactionSessionRunner.java:168)
	at io.mycat.runtime.MycatDataContextImpl.block(MycatDataContextImpl.java:329)
	at io.mycat.ReceiverImpl.block(ReceiverImpl.java:444)
	at io.mycat.ReceiverImpl.execute(ReceiverImpl.java:332)
	at io.mycat.ReceiverImpl.proxySelect(ReceiverImpl.java:103)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.lambda$onSelectTable$3(SelectSQLHandler.java:225)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThread.processJob(BindThread.java:92)
	at io.mycat.bindThread.BindThread.run(BindThread.java:52)
	at io.mycat.bindThread.BindThreadPool.runOnBinding(BindThreadPool.java:176)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:126)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:111)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:138)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.block(ServerTransactionSessionRunner.java:168)
	at io.mycat.runtime.MycatDataContextImpl.block(MycatDataContextImpl.java:329)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.onSelectTable(SelectSQLHandler.java:212)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.lambda$onExecute$4(SelectSQLHandler.java:255)
	at java.util.Optional.map(Optional.java:215)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.onExecute(SelectSQLHandler.java:255)
	at io.mycat.sqlHandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:29)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:154)
	at io.mycat.commands.MycatdbCommand.run(MycatdbCommand.java:97)
	at io.mycat.client.UserSpace.execute(UserSpace.java:134)
	at io.mycat.client.UserSpace.execute(UserSpace.java:81)
	at io.mycat.DefaultCommandHandler.handleQuery(DefaultCommandHandler.java:69)
	at io.mycat.command.ThreadModeCommandDispatcher.lambda$handleQuery$0(ThreadModeCommandDispatcher.java:26)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThread.processJob(BindThread.java:92)
	at io.mycat.bindThread.BindThread.run(BindThread.java:70)
] with root cause

java.sql.SQLException:  HY000 java.lang.IllegalArgumentException
	at io.mycat.ReceiverImpl.lambda$execute$8(ReceiverImpl.java:342)
	at io.mycat.ReceiverImpl.lambda$block$12(ReceiverImpl.java:444)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThread.processJob(BindThread.java:92)
	at io.mycat.bindThread.BindThread.run(BindThread.java:52)
	at io.mycat.bindThread.BindThreadPool.runOnBinding(BindThreadPool.java:176)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:126)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:111)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:138)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.block(ServerTransactionSessionRunner.java:168)
	at io.mycat.runtime.MycatDataContextImpl.block(MycatDataContextImpl.java:329)
	at io.mycat.ReceiverImpl.block(ReceiverImpl.java:444)
	at io.mycat.ReceiverImpl.execute(ReceiverImpl.java:332)
	at io.mycat.ReceiverImpl.proxySelect(ReceiverImpl.java:103)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.lambda$onSelectTable$3(SelectSQLHandler.java:225)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThread.processJob(BindThread.java:92)
	at io.mycat.bindThread.BindThread.run(BindThread.java:52)
	at io.mycat.bindThread.BindThreadPool.runOnBinding(BindThreadPool.java:176)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:126)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:111)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:138)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.block(ServerTransactionSessionRunner.java:168)
	at io.mycat.runtime.MycatDataContextImpl.block(MycatDataContextImpl.java:329)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.onSelectTable(SelectSQLHandler.java:212)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.lambda$onExecute$4(SelectSQLHandler.java:255)
	at java.util.Optional.map(Optional.java:215)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.onExecute(SelectSQLHandler.java:255)
	at io.mycat.sqlHandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:29)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:154)
	at io.mycat.commands.MycatdbCommand.run(MycatdbCommand.java:97)
	at io.mycat.client.UserSpace.execute(UserSpace.java:134)
	at io.mycat.client.UserSpace.execute(UserSpace.java:81)
	at io.mycat.DefaultCommandHandler.handleQuery(DefaultCommandHandler.java:69)
	at io.mycat.command.ThreadModeCommandDispatcher.lambda$handleQuery$0(ThreadModeCommandDispatcher.java:26)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThread.processJob(BindThread.java:92)
	at io.mycat.bindThread.BindThread.run(BindThread.java:70)
开启xa，insert正常，查询报以上错误

**Comment by junwen12221** [comment]
最新提交已经修复

**Comment by junwen12221** [comment]
mycat2.0 服务端开启xa，客户端insert 事务正常，但是查询出现异常；
mycat2.0 服务端不开启xa，客户端insert异常，但是查询正常


都是这个异常?

**Comment by superBinLiu** [comment]
是的，验证了下，部分解决。问题：xa分布式事务 insert 第一成功，insert第二次由于主键已存在会失败，但是rollback失败，到时数据库被锁。
![image](https://user-images.githubusercontent.com/62001174/84498045-742e5000-ace2-11ea-9838-1c01f30f152e.png)
![image](https://user-images.githubusercontent.com/62001174/84498069-801a1200-ace2-11ea-900f-905027bf531d.png)

**Comment by junwen12221** [comment]
是异常的时候rollback没有被调用吗,这个还可以改下.锁了可能要等超时,或者有一个服务轮训mysql的事务表,把锁了的,杀掉

**Comment by junwen12221** [comment]
主键已经存在要开全局序列号,或者应用给出唯一主键

**Comment by junwen12221** [comment]
xa回滚死锁已经修复

**Comment by superBinLiu** [comment]
sql 语句中存在">","<"比较符时，出错。
![image](https://user-images.githubusercontent.com/62001174/84768550-fed6be00-b006-11ea-9bd7-2a73d14b1c20.png)

**Comment by Tracy82** [comment]
我这边的项目中也碰到了这个问题,sql语句中存在“<”,">"等比较符就报错。

**Comment by junwen12221** [comment]
这个UnionPullConstant规则的问题在master分支的代码已经修复了
