### ISSUE TITLE
【配置问题】mycat2-1.03-SNAPSHOT.jar 启动报错

### ISSUE THREAD

**Issue by mylovesky** [MyCATApache/Mycat2#383]
metadata: #读写分离无需配置
  schemas: [{ schemaName: 'zwfw' ,   targetName: 'repli', shadingTables: {},
            globalTables: {
              company:{
                dataNodes: [ {targetName: zwfw_5 ,schemaName: zwfw, tableName: sys_file}
          }]
interceptors:
    [{user:{username: 'root' ,password: '12345678' , ip: '.'}}]
报错：
Caused by: Cannot create property=schemas for JavaBean=ShardingQueryRootConfig(schemas={}, prototype=null)
 in 'string', line 5, column 3:
      schemas: [{ schemaName: 'zwfw' , ... 
      ^
No suitable constructor with 1 arguments found for interface java.util.Map
 in 'string', line 5, column 12:
      schemas: [{ schemaName: 'zwfw' ,   target ... 
               ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:270)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246)
	... 13 more
Caused by: org.yaml.snakeyaml.error.YAMLException: No suitable constructor with 1 arguments found for interface java.util.Map
	at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:584)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:247)
	... 18 more

**Comment by junwen12221** [comment]
这个应该是配置问题,可以看一下example文件夹的例子对应,每个版本的配置细节有一点不一样,都会导致加载失败

**Comment by mylovesky** [comment]
请问这个问题 能解决吗，这个aarch64 我一直找不到

Unable to locate any of the following operational binaries:
  /apps/apply/mycat/mycat/bin/./wrapper-linux-aarch64-64
  /apps/apply/mycat/mycat/bin/./wrapper-linux-aarch64-32
  /apps/apply/mycat/mycat/bin/./wrapper
