### ISSUE TITLE
这个prototype是个什么？有没有一个完整的配置示例。

### ISSUE THREAD

**Issue by iamif3000** [MyCATApache/Mycat2#411]
有没有一个完整的示例。对wiki着配，都配不好。（手动流泪。。。）
```
jvm 1    | WrapperSimpleApp: Encountered an error running main: java.lang.NullPointerException: unknown target:prototype
jvm 1    | java.lang.NullPointerException: unknown target:prototype
jvm 1    |      at java.util.Objects.requireNonNull(Objects.java:290)
jvm 1    |      at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:120)
jvm 1    |      at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:115)
jvm 1    |      at io.mycat.metadata.MetadataManager.<init>(MetadataManager.java:133)
jvm 1    |      at io.mycat.ConfigPrepareExecuter.initBy(ConfigPrepareExecuter.java:148)
jvm 1    |      at io.mycat.ConfigPrepareExecuter.prepareRuntimeObject(ConfigPrepareExecuter.java:106)
jvm 1    |      at io.mycat.FileMetadataStorageManager$1.commit(FileMetadataStorageManager.java:222)
jvm 1    |      at io.mycat.FileMetadataStorageManager.start(FileMetadataStorageManager.java:179)
jvm 1    |      at io.mycat.MycatCore.start(MycatCore.java:94)
jvm 1    |      at io.mycat.MycatCore.main(MycatCore.java:99)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    |      at java.lang.reflect.Method.invoke(Method.java:498)
jvm 1    |      at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
jvm 1    |      at java.lang.Thread.run(Thread.java:748)
wrapper  | <-- Wrapper Stopped

```

![image](https://user-images.githubusercontent.com/16129632/101738728-89edc800-3b01-11eb-9e79-999b95285ceb.png)

在linux上
![image](https://user-images.githubusercontent.com/16129632/101738992-e51fba80-3b01-11eb-81f0-33afc5545160.png)
如果不在前面调用toAbsolutePath()，会有问题。

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat2/wiki/%5B%E7%AE%80%E4%BB%8B%5D%E8%BD%AF%E4%BB%B6%E6%9E%B6%E6%9E%84
https://github.com/MyCATApache/Mycat2/wiki/%5B%E7%AE%80%E4%BB%8B%5D%E5%85%A5%E9%97%A8Mycat2
prototype需要指向处理兼容性sql的mysql服务器

你截图的代码不是最新的

**Comment by iamif3000** [comment]
是 v1.13-alpha 这个tag的代码。
我这里看不到github的图，错了不少内容啊。
现在翻墙看到了。多谢。

**Comment by junwen12221** [comment]
这个版本的配置文件还在变化,建议直接使用注解或者建库建表sql操作.有任何建议可以留言
