### ISSUE TITLE
支持SELECT ROW_COUNT();

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#494]
更新、插入后需要知道影响的行数。现在未支持。

```
SELECT ROW_COUNT()
> 0 -  HY000java.lang.IllegalStateException: Unable to implement MycatProject(ROW_COUNT()=[ROW_COUNT()]): rowcount = 1.0, cumulative cost = {2.0 rows, 2.0 cpu, 0.0 io}, id = 5545
  MycatValues(tuples=[[{ 0 }]]): rowcount = 1.0, cumulative cost = {1.0 rows, 1.0 cpu, 0.0 io}, id = 5542

	at io.mycat.calcite.MycatEnumerableRelImplementor.implementRoot(MycatEnumerableRelImplementor.java:41)
	at io.mycat.DrdsRunner.getCodeExecuterContext(DrdsRunner.java:613)
	at io.mycat.DrdsRunner.convertToExecuter(DrdsRunner.java:6
```

**Comment by junwen12221** [comment]
好的.我们这边用的jdbc驱动,会从报文里面获取该值,支持这个函数也是可以的,比较简单

**Comment by imxmj** [comment]
@junwen12221 好的，这个是在插入或更新语句后生成的，形如
```
UPDATE `TABLE` SET `XX`='YYY` WHERE `ID` = 123;
SELECT ROW_COUNT();
```

**Comment by imxmj** [comment]
@junwen12221 好的，这个是在插入或更新语句后生成的，形如
UPDATE `TABLE` SET `XX`='YYY` WHERE `ID` = 123;
SELECT ROW_COUNT();

**Comment by imxmj** [comment]
@junwen12221 好的，这个是在插入或更新语句后生成的，形如
UPDATE `TABLE` SET `XX`='YYY` WHERE `ID` = 123;
SELECT ROW_COUNT();
