### ISSUE TITLE
mycat2 启动失败

### ISSUE THREAD

**Issue by zealinux** [MyCATApache/Mycat2#500]
日志如下：

```
STATUS | wrapper  | 2021/02/25 14:50:40 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2021/02/25 14:50:41 | Launching a JVM...
INFO   | jvm 1    | 2021/02/25 14:50:41 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2021/02/25 14:50:41 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2021/02/25 14:50:41 |
INFO   | jvm 1    | 2021/02/25 14:50:41 |
INFO   | jvm 1    | 2021/02/25 14:50:41 | WrapperSimpleApp: Encountered an error running main: java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2021/02/25 14:50:41 | java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at io.mycat.MycatCore.<init>(MycatCore.java:60)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at io.mycat.MycatCore.main(MycatCore.java:154)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2021/02/25 14:50:41 | Caused by: java.lang.RuntimeException: while resolving method 'bindObservable[interface org.apache.calcite.runtime.NewMycatDataContext]' in class interface org.apache.calcite.runtime.Bindable
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at org.apache.calcite.linq4j.tree.Types.lookupMethod(Types.java:323)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at org.apache.calcite.util.RxBuiltInMethod.<init>(RxBuiltInMethod.java:70)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at org.apache.calcite.util.RxBuiltInMethod.<clinit>(RxBuiltInMethod.java:34)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       ... 8 more
INFO   | jvm 1    | 2021/02/25 14:50:41 | Caused by: java.lang.NoSuchMethodException: org.apache.calcite.runtime.Bindable.bindObservable(org.apache.calcite.runtime.NewMycatDataContext)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at java.lang.Class.getMethod(Class.java:1786)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       at org.apache.calcite.linq4j.tree.Types.lookupMethod(Types.java:314)
INFO   | jvm 1    | 2021/02/25 14:50:41 |       ... 10 more
STATUS | wrapper  | 2021/02/25 14:50:44 | <-- Wrapper Stopped
```

环境：
mycat2-1.15-dev, Mac, Java 8 or Java 15

**Comment by junwen12221** [comment]
收到

**Comment by imxmj** [comment]
@junwen12221 1.15-dev 2021-2-25版本同样有这个问题

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.15-dev/2021-2-26/

这个修复了

**Comment by imxmj** [comment]
@junwen12221 启动没问题了，当naivcat连接时报这个错。

```
INFO   | jvm 1    | 2021/02/26 10:39:05 | [vertx-mycat-7] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
INFO   | jvm 1    | 2021/02/26 10:39:05 | java.lang.NoClassDefFoundError: Could not initialize class io.vertx.core.buffer.impl.VertxByteBufAllocator
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:72)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:68)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.impl.BufferImpl.buffer(BufferImpl.java:46)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.Buffer.buffer(Buffer.java:49)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.mycat.vertx.VertxMySQLAuthHandler.<init>(VertxMySQLAuthHandler.java:37)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.mycat.vertx.VertxMycatServer$MycatSessionManager.lambda$start$0(VertxMycatServer.java:88)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:123)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at java.lang.Thread.run(Thread.java:748)

```
java版本
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

**Comment by junwen12221** [comment]
> @junwen12221 启动没问题了，当naivcat连接时报这个错。
> 
> ```
> INFO   | jvm 1    | 2021/02/26 10:39:05 | [vertx-mycat-7] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
> INFO   | jvm 1    | 2021/02/26 10:39:05 | java.lang.NoClassDefFoundError: Could not initialize class io.vertx.core.buffer.impl.VertxByteBufAllocator
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:72)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:68)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.impl.BufferImpl.buffer(BufferImpl.java:46)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.buffer.Buffer.buffer(Buffer.java:49)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.mycat.vertx.VertxMySQLAuthHandler.<init>(VertxMySQLAuthHandler.java:37)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.mycat.vertx.VertxMycatServer$MycatSessionManager.lambda$start$0(VertxMycatServer.java:88)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:123)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> INFO   | jvm 1    | 2021/02/26 10:39:05 | 	at java.lang.Thread.run(Thread.java:748)
> ```
> 
> java版本
> openjdk version "1.8.0_262"
> OpenJDK Runtime Environment (build 1.8.0_262-b10)
> OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

更新了 11:21

**Comment by imxmj** [comment]
更新的版本依然存在上面问题哈。
ls -tl
```
-rw-rw-r-- 1 audit audit    22948 Feb 26 11:20 libwrapper-aix-ppc-32.a
-rw-rw-r-- 1 audit audit    24499 Feb 26 11:20 libwrapper-aix-ppc-64.a
-rw-rw-r-- 1 audit audit    74520 Feb 26 11:20 libwrapper-hpux-parisc-64.sl
-rw-rw-r-- 1 audit audit    23839 Feb 26 11:20 libwrapper-linux-ppc-64.so
-rw-rw-r-- 1 audit audit    11887 Feb 26 11:20 libwrapper-linux-x86-32.so
...
```

**Comment by junwen12221** [comment]
我刚才重现了,又更新了
看来vertx4.0.2还有这个问题,是偶发的

https://stackoverflow.com/questions/65903988/java-lang-illegalaccesserror-when-using-vertx-web-client-version-4-0-0
根据这个帖子添加了

     <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.48.Final</version>
        </dependency>

**Comment by imxmj** [comment]
修改了包对了，但是你发布的版本中包不对，我下载4.1.48.Final版本替换就ok。
