### ISSUE TITLE
分片表查询的别名支持问题

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#501]
创建表，并对traveldate进行YYYYMM分片
```
CREATE TABLE `travelrecord2` (
  `id` bigint(20) NOT NULL KEY,
  `user_id` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `traveldate` datetime DEFAULT NULL,
  `fee` decimal(10,0) DEFAULT NULL,
  `days` int(11) DEFAULT NULL,
  `blob` longblob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
tbpartition by YYYYMM(traveldate) tbpartitions 12;
```
创建主表
```
CREATE TABLE `user` (
  `id` int NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
使用以下查询语句进行查询可以返回正确结果
```
SELECT t1.id,t1.name,t2.count FROM mycat_testdb.user as t1
left join (select count(1) as `count`,`user_id` from travelrecord2 group by `user_id`) 
as t2 on `t1`.`id` = `t2`.`user_id`;
```
当给t2表加入反引号时，执行报错
```
SELECT t1.id,t1.name,t2.count FROM mycat_testdb.user as t1
left join (select count(1) as `count`,`user_id` from travelrecord2 group by `user_id`) 
as `t2` on `t1`.`id` = `t2`.`user_id`;
```
错误信息
```
0 -  HY000org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: Table 't2' not found
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Construc
```
对于没有分片的表以上两种方式都是支持的。

**Comment by junwen12221** [comment]
好的
