### ISSUE TITLE
支持默认返回多个数据集

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#505]
在更新和插入的时候通过SELECT ROW_COUNT()返回受影响的行数，默认返回的结果是singleRow，某些ORM框架读取的方式是multi result set,导致读取失败。希望能实现通过配置来设置返回的结果集，或默认返回multi result set。

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.15-dev/2021-2-26/

更新了,默认支持返回多结果集

**Comment by imxmj** [comment]
启动mycat执行
```
START TRANSACTION
INSERT INTO `travelrecord` (`blob`, `days`, `fee`, `traveldate`, `user_id`)
VALUES (NULL, 3, 3, timestamp('2021-02-21 12:23:42.058156'), 'tom');
SELECT ROW_COUNT();
COMMIT;
```
报错
```
jvm 1    | [vertx-mycat-12] ERROR io.mycat.MycatDataContext -
jvm 1    | java.lang.IllegalAccessError: class io.mycat.calcite.MycatCalciteSupport tried to access private field org.apache.calcite.adapter.enumerable.RexImpTable.map (io.mycat.calcite.MycatCalciteSupport and org.apache.calcite.adapter.enumerable.RexImpTable are in unnamed module of loader 'app')
jvm 1    |      at io.mycat.calcite.MycatCalciteSupport.<clinit>(MycatCalciteSupport.java:234)
jvm 1    |      at io.mycat.DrdsRunner.getRelRoot(DrdsRunner.java:458)
jvm 1    |      at io.mycat.DrdsRunner.compileQuery(DrdsRunner.java:422)
```

**Comment by imxmj** [comment]
很奇怪，通过ORM访问mycat进行更新， mycat返回了UNKNOWN.ROW_COUNT()报文
```
0000   3c 7c 3f 2b d7 be 40 16 7e 72 ed d2 08 00 45 00   <|?+..@.~r....E.
0010   00 76 b6 65 40 00 40 06 ff 94 c0 a8 01 c9 c0 a8   .v.e@.@.........
0020   01 6e 1f 82 d2 3b 31 97 72 fb 1e 1b 0a 73 50 18   .n...;1.r....sP.
0030   01 06 ba df 00 00 41 00 00 03 03 64 65 66 07 55   ......A....def.U
0040   4e 4b 4e 4f 57 4e 07 55 4e 4b 4e 4f 57 4e 07 55   NKNOWN.UNKNOWN.U
0050   4e 4b 4e 4f 57 4e 0b 52 4f 57 5f 43 4f 55 4e 54   NKNOWN.ROW_COUNT
0060   28 29 0b 52 4f 57 5f 43 4f 55 4e 54 28 29 0c 21   ().ROW_COUNT().!
0070   00 00 01 00 00 08 00 00 00 00 00 05 00 00 04 fe   ................
0080   00 00 03 00                                       ....
```

**Comment by imxmj** [comment]
很奇怪，通过ORM访问mycat进行更新， mycat返回了UNKNOWN.ROW_COUNT()报文
```
0000   3c 7c 3f 2b d7 be 40 16 7e 72 ed d2 08 00 45 00   <|?+..@.~r....E.
0010   00 76 b6 65 40 00 40 06 ff 94 c0 a8 01 c9 c0 a8   .v.e@.@.........
0020   01 6e 1f 82 d2 3b 31 97 72 fb 1e 1b 0a 73 50 18   .n...;1.r....sP.
0030   01 06 ba df 00 00 41 00 00 03 03 64 65 66 07 55   ......A....def.U
0040   4e 4b 4e 4f 57 4e 07 55 4e 4b 4e 4f 57 4e 07 55   NKNOWN.UNKNOWN.U
0050   4e 4b 4e 4f 57 4e 0b 52 4f 57 5f 43 4f 55 4e 54   NKNOWN.ROW_COUNT
0060   28 29 0b 52 4f 57 5f 43 4f 55 4e 54 28 29 0c 21   ().ROW_COUNT().!
0070   00 00 01 00 00 08 00 00 00 00 00 05 00 00 04 fe   ................
0080   00 00 03 00                                       ....
```

**Comment by imxmj** [comment]
很奇怪，通过ORM访问mycat进行更新， mycat返回了UNKNOWN.ROW_COUNT()报文
```
0000   3c 7c 3f 2b d7 be 40 16 7e 72 ed d2 08 00 45 00   <|?+..@.~r....E.
0010   00 76 b6 65 40 00 40 06 ff 94 c0 a8 01 c9 c0 a8   .v.e@.@.........
0020   01 6e 1f 82 d2 3b 31 97 72 fb 1e 1b 0a 73 50 18   .n...;1.r....sP.
0030   01 06 ba df 00 00 41 00 00 03 03 64 65 66 07 55   ......A....def.U
0040   4e 4b 4e 4f 57 4e 07 55 4e 4b 4e 4f 57 4e 07 55   NKNOWN.UNKNOWN.U
0050   4e 4b 4e 4f 57 4e 0b 52 4f 57 5f 43 4f 55 4e 54   NKNOWN.ROW_COUNT
0060   28 29 0b 52 4f 57 5f 43 4f 55 4e 54 28 29 0c 21   ().ROW_COUNT().!
0070   00 00 01 00 00 08 00 00 00 00 00 05 00 00 04 fe   ................
0080   00 00 03 00                                       ....
```

**Comment by imxmj** [comment]
对于这种更新语句`UPDATE XX SET YY=ZZ WHERE ...;SELECT ROW_COUNT();` 通过Navicat执行，查看报文是分开执行的，可以返回正确结果；ORM是整个语句一起执行的，mycat就会返回上述报文。

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.15-dev/2021-2-27/

**Comment by imxmj** [comment]
这次看返回报文没有UNKNOWN字样，但是跟mysql返回的字样有些差别，导致客户端度取到错误的报文

mycat返回报文
```
0000   3c 7c 3f 2b d7 be 40 16 7e 72 ed d2 08 00 45 00   <|?+..@.~r....E.
0010   00 61 25 3f 40 00 40 06 90 d0 c0 a8 01 c9 c0 a8   .a%?@.@.........
0020   01 6e 1f 82 e5 d0 c0 ba 92 46 d1 6b 0e cc 50 18   .n.......F.k..P.
0030   00 f5 b1 a8 00 00 2c 00 00 03 03 64 65 66 00 00   ......,....def..
0040   00 0b 52 4f 57 5f 43 4f 55 4e 54 28 29 0b 52 4f   ..ROW_COUNT().RO
0050   57 5f 43 4f 55 4e 54 28 29 0c 21 00 00 01 00 00   W_COUNT().!.....
0060   08 00 00 00 00 00 05 00 00 04 fe 00 00 03 00      ...............
```
mysql返回报文
```
0000   3c 7c 3f 2b d7 be 40 16 7e 72 ed d2 08 00 45 00   <|?+..@.~r....E.
0010   00 63 50 35 40 00 40 06 65 d8 c0 a8 01 c9 c0 a8   .cP5@.@.e.......
0020   01 6e 0c ea e5 e1 2f 58 13 80 72 13 8c 22 50 18   .n..../X..r.."P.
0030   00 f5 42 25 00 00 01 00 00 02 01 21 00 00 03 03   ..B%.......!....
0040   64 65 66 00 00 00 0b 52 4f 57 5f 43 4f 55 4e 54   def....ROW_COUNT
0050   28 29 00 0c 3f 00 15 00 00 00 08 81 00 00 00 00   ()..?...........
0060   02 00 00 04 01 31 07 00 00 05 fe 00 00 02 00 00   .....1..........
0070   00          
```                                
def ROW_COUNT ? 1 应该表示的是返回的影响行数ROW_COUNT为1
