### ISSUE TITLE
decimal 数据类型引起语法错误

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#508]
按日期分表，字段类型为decimal，客户端参数化的sql语句在mycat一侧生成的语句为 `'DECIMAL '2.00', `Balance` = DECIMAL '898.00' `，mycat无法识别报错。
```
HY000java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DECIMAL '-0.5', DECIMAL '980.5', 1, 'hcd00002'
	, timestamp('2021-03-01 11:30:53' at line 4
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:781)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:437)
	at io.mycat.vertxmycat.JdbcMySqlConnection$JdbcQuery.innerExecute(JdbcMySqlConnection.java:149)
	at io.mycat.vertxmycat.JdbcMySqlConnection$JdbcQuery.lambda$null$0(JdbcMySqlConnection.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by imxmj** [comment]
测试用例
```
CREATE TABLE `travelrecord2` (
  `id` bigint(20) NOT NULL KEY,
  `user_id` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `traveldate` datetime DEFAULT NULL,
  `fee` decimal(10,0) DEFAULT NULL,
  `days` int(11) DEFAULT NULL,
  `blob` longblob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
tbpartition by YYYYMM(traveldate) tbpartitions 12;

INSERT INTO `travelrecord2`(`id`,`user_id`,`traveldate`,`fee`,`days`,`blob`)
VALUES (1,2,timestamp('2021-02-22 18:34:05.983692'),3.5,4,NULL)；
```
错误如下：
```
 INSERT INTO `travelrecord2`(`id`,`user_id`,`traveldate`,`fee`,`days`,`blob`)
VALUES (1,2,timestamp('2021-02-22 18:34:05.983692'),3.5,4,NULL)
> 0 -  HY000java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DECIMAL '3.5', 4
 , NULL)' at line 3
 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
```
