### ISSUE TITLE
分片表查询报错

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#511]
按以下步骤执行
```
create database mycat_testdb;
use mycat_testdb;
/*+ mycat:createDataSource{
"name":"dw0",
"url":"jdbc:mysql://127.0.0.1:3306",
"user":"root",
"password":"123456"
} */;
/*+ mycat:createDataSource{
"name":"dr0",
"url":"jdbc:mysql://127.0.0.1:3306",
"user":"root",
"password":"123456"
} */;
/*! mycat:createCluster{"name":"c0","masters":["dw0"],"replicas":["dr0"]} */;
CREATE TABLE `travelrecord2` (
  `id` bigint(20) NOT NULL KEY,
  `user_id` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `traveldate` datetime DEFAULT NULL,
  `fee` decimal(10,0) DEFAULT NULL,
  `days` int(11) DEFAULT NULL,
  `blob` longblob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
tbpartition by YYYYMM(traveldate) tbpartitions 12;
```
然后执行查询语句报错：`SELECT * FROM travelrecord2;`

错误信息如下：
```
> 0 -  HY000java.lang.IllegalAccessError: tried to access field org.apache.calcite.adapter.enumerable.RexImpTable.map from class io.mycat.calcite.MycatCalciteSupport
	at io.mycat.calcite.MycatCalciteSupport.<clinit>(MycatCalciteSupport.java:234)
	at io.mycat.DrdsRunner.getRelRoot(DrdsRunner.java:458)
	at io.mycat.DrdsRunner.compileQuery(DrdsRunner.java:422)
	at io.mycat.DrdsRunner.dispatch(DrdsRunner.java:265)
	at io.mycat.DrdsRunner.convertToMycatRel(DrdsRunner.java:253)
	at io.mycat.DrdsRunner.convertToMycatRe
```

**Comment by imxmj** [comment]
jdk版本为1.8
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
```
