### ISSUE TITLE
MySqlException: HY000 io.mycat.MycatException: unsupport!

### ISSUE THREAD

**Issue by coder-ds** [MyCATApache/Mycat2#531]
mycat部署好以后，连接项目，然后获取数据刷新页面就会报错。
有点类似1.6版本时候的ignoreUnknownCommand 不是到2.0以后有没有什么配置

**Exception**
16:13:36 T=Thread-1 [io.mycat.proxy.session.Session error at 252]-[ERROR] 
io.mycat.MycatException: unsupport!
	at io.mycat.proxy.session.MycatSession.resetSession(MycatSession.java:341)
	at io.mycat.command.AbstractCommandHandler.handleResetConnection(AbstractCommandHandler.java:112)
	at io.mycat.command.ThreadModeCommandDispatcher.lambda$handleResetConnection$21(ThreadModeCommandDispatcher.java:131)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:145)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:118)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:110)
	at io.mycat.proxy.session.ServerTransactionSessionRunner.run(ServerTransactionSessionRunner.java:137)
	at io.mycat.runtime.MycatDataContextImpl.run(MycatDataContextImpl.java:269)
	at io.mycat.command.ThreadModeCommandHanlderImpl.run(ThreadModeCommandHanlderImpl.java:17)
	at io.mycat.command.ThreadModeCommandDispatcher.handleResetConnection(ThreadModeCommandDispatcher.java:131)
	at io.mycat.command.CommandResolver.handle(CommandResolver.java:335)
	at io.mycat.proxy.handler.MycatHandler.onSocketRead(MycatHandler.java:54)
	at io.mycat.proxy.handler.MycatHandler.onSocketRead(MycatHandler.java:33)
	at io.mycat.proxy.reactor.ProxyReactorThread.processReadKey(ProxyReactorThread.java:149)
	at io.mycat.proxy.reactor.ProxyReactorThread.run(ProxyReactorThread.java:206)

**个人配置文件**
metadata: #读写分离无需配置
interceptors:
  [{user:{username: 'root' ,password: '123456' , ip: ''},
    defaultHanlder: {command: execute , tags: {targets: repli,needTransaction: true,executeType: QUERY}},
    sqls:[
    {sql: 'insert {any}',command: execute , tags: {targets: defaultDs,needTransaction: true,executeType: INSERT }} ,
    {sql: 'delete {any}',command: execute , tags: {targets: defaultDs,needTransaction: true,executeType: UPDATE} } ,
    {sql: 'show {any}',command: execute , tags: {targets: defaultDs}}
    ] ,
    sqlsGroup: [*jdbcAdapter],
    transactionType: proxy  #xa.proxy
   }]
datasource:
  datasources: [{name: defaultDs, ip: 192.168.1.211,port: 3306,user: admin,password: ****,maxCon: 10000,minCon: 0,
                 maxRetryCount: 3, #连接重试次数
                 maxConnectTimeout: 10000, #连接超时时间 毫秒
                 dbType: mysql, #
                 initSqls: ['use nfh_sfa'],
                 weight: 1, #负载均衡权重
                 instanceType:,#READ,WRITE,READ_WRITE ,集群信息中是主节点,则默认为读写,副本则为读,此属性可以强制指定可写,
                },
                {name: defaultDs2, ip: 192.168.1.212,port: 3306,user: admin,password: ****,maxCon: 10000,
                 initSqls: ['use nfh_sfa'],
                 minCon: 0,maxRetryCount: 3,maxConnectTimeout: 10000,dbType: mysql,weight: 1,instanceType:,#READ,WRITE,READ_WRITE
                }
  ]
  timer: {initialDelay: 10, period: 5, timeUnit: SECONDS}
cluster: #集群,数据源选择器,既可以mycat自行检查数据源可用也可以通过mycat提供的外部接口设置设置数据源可用信息影响如何使用数据源
  close: true  #关闭集群心跳,此时集群认为所有数据源都是可用的,可以通过mycat提供的外部接口设置数据源可用信息达到相同效果
  clusters: [
  {name: repli ,
   replicaType: MASTER_SLAVE , # SINGLE_NODE:单一节点 ,MASTER_SLAVE:普通主从 GARELA_CLUSTER:garela cluster
   switchType: SWITCH , #NOT_SWITCH:不进行主从切换,SWITCH:进行主从切换
   readBalanceType: BALANCE_ALL  , #对于查询请求的负载均衡类型
   readBalanceName: BalanceRoundRobin , #对于查询请求的负载均衡类型
   writeBalanceName: BalanceRoundRobin ,  #对于修改请求的负载均衡类型
   masters:[defaultDs , defaultDs2], #主节点列表,普通主从,当主失去连接后,依次选择列表中存活的作为主节点
   replicas:[ defaultDs2],#从节点列表
   maxCon:, #集群最占用大连接限制
   heartbeat:{maxRetry: 3, #心跳重试次数
              minSwitchTimeInterval: 120000 , #最小主从切换间隔
              heartbeatTimeout: 100000 , #心跳超时值,毫秒
              slaveThreshold: 0 , # mysql binlog延迟值
              reuqestType: 'mysql' #进行心跳的方式,mysql或者jdbc两种
   }}
  ]
  timer: {initialDelay: 0, period: 1, timeUnit: SECONDS} #心跳定时器 initialDelay一般为0,mycat会在开启集群心跳,一个initialDelay+1秒之后开启服务器端口
server:
  ip: 192.168.1.**
  port: 8066
  reactorNumber: 1
  #用于多线程任务的线程池,
  worker: {close: true, #禁用多线程池,jdbc等功能将不能使用
           maxPengdingLimit: 65535, #每个线程处理任务队列的最大长度
           maxThread: 1,
           minThread: 1,
           timeUnit: SECONDS,
           waitTaskTimeout: 5 #超时后将结束闲置的线程
  }

**Comment by junwen12221** [comment]
请用最新版 1.17或者1.18-dev
