### ISSUE TITLE
引发嵌套事务

### ISSUE THREAD

**Issue by coder-ds** [MyCATApache/Mycat2#539]
**HY000java.lang.IllegalArgumentException: occur Nested transaction**
现在做了读写分离，主库用的InnoDB，从库用的MyISAM。
偶尔会出现引发嵌套事务，然后配置"transactionType":"proxy"
请问这个问题有没有什么解决方案。

2021-04-30 11:02:55
HY000java.lang.IllegalArgumentException: occur Nested transaction
at cn.mycat.vertx.xa.impl.LocalSqlConnection.begin(LocalSqlConnection.java:55)
at io.mycat.commands.ReceiverImpl.begin(ReceiverImpl.java:118)
at io.mycat.sqlhandler.dcl.StartTransactionSQLHandler.onExecute(StartTransactionSQLHandler.java:29)
at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:52)
at io.mycat.commands.MycatdbCommand.lambda$execute$0(MycatdbCommand.java:197)
at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
at io.vertx.core.Future.compose(Future.java:199)
at io.vertx.core.Future.flatMap(Future.java:180)
at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:184)
at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:157)
at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:150)
at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
at io.vertx.core.Future.compose(Future.java:199)
at io.vertx.core.Future.flatMap(Future.java:180)
at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:150)
at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:545)
at io.mycat.mycatmysql.MycatVertxMySQLHandler.handle0(MycatVertxMySQLHandler.java:122)
at io.mycat.mycatmysql.MycatVertxMySQLHandler.handle(MycatVertxMySQLHandler.java:87)
at io.mycat.vertx.VertxMySQLPacketResolver.handle(VertxMySQLPacketResolver.java:98)
at io.mycat.vertx.VertxMySQLPacketResolver.handle(VertxMySQLPacketResolver.java:26)
at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:397)
at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:90)
at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:378)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:123)
at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Unknown Source)

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.17-release/2021-4-30-nested-transcation/

检查出错的业务代码是否试图在已经有事务的状态再开启事务,如果不能解决可以使用上述地址的jar
