### ISSUE TITLE
第一次用mycat2，配置schema.json 后，插入数据时报表不存在是哪里配置有问题？

### ISSUE THREAD

**Issue by mkerj** [MyCATApache/Mycat2#553]
schema配置如下：
{
  "schemaName": "wecandbtest_v1",
  "customTables": {},
  "globalTables": {},
  "normalTables": {
    "wc_batchs": {
      "locality": {
        "schemaName":"wecandbtest_v1",
        "tableName":"wc_batchs",
        "targetName":"prototype"
      }
    }
  },
  "shadingTables":{
      "wc_advert_resources":{
        "createTableSQL": "CREATE TABLE `wc_advert_resources` (`id` bigint NOT NULL AUTO_INCREMENT COMMENT '逻辑ID',`sourceUrl` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT ''  ......) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='广告资源';",
        "function":{
          "clazz":"io.mycat.router.mycat1xfunction.PartitionByMod",
          "properties": {
            "columnName": "id",
            "count": "50",
          },
          "ranges":{}
        },
        "partition": {
          "targetNames": "prototype",
          "schemaNames":"wecandbtest_v1",
          "tableNames":"wc_advert_resources_$0-49"
        }
      }
    }
}

报错如下：
HY000java.sql.BatchUpdateException: Table 'wecandbtest_v1.wc_advert_resources_1' doesn't exist

**Comment by junwen12221** [comment]
存储节点没有这个wecandbtest_v1.wc_advert_resources_1表

**Comment by junwen12221** [comment]
你直接通过配置文件配置的话,是需要自己配置mysql上面的分表.而使用建表语句则不需要,是在执行建表语句的时候,会自动建立物理表

**Comment by mkerj** [comment]
谢谢~我手动执行创表语句后，会生成 0-59张表，但是我在批量插入数据的时候，没有分表存储，这是哪里配置有问题呢？

**Comment by mkerj** [comment]
@junwen12221 谢谢~我手动执行创表语句后，会生成 0-59张表，但是我在批量插入数据的时候，没有分表存储，这是哪里配置有问题呢？

**Comment by junwen12221** [comment]
/*+ mycat:showTopology{
  "schemaName":"wecandbtest_v1",
  "tableName":"wc_advert_resources"
} */;

查看mycat2内的表映射结构,并检查物理表上有没有对应的表

**Comment by mkerj** [comment]
@junwen12221 谢谢~ 我在全局表配置映射关系后可以正常访问了，但是我在 shadingTables，里面配置了多个表就又报错了，这是哪里的问题呢？如果只保留一张表不会报错。

配置内容如下：
 "shadingTables": {
                "wc_advert_resources":{
                        "createTableSQL":"......",
                        "function":{
                                "clazz":"io.mycat.router.mycat1xfunction.PartitionByMod",
                                "properties":{
                                        "count":"80",
                                        "columnName":"id"
                                },
                                "ranges":{}
                        },
                        "partition":{
                                "schemaNames":"mycat2db",
                                "tableNames":"wc_advert_resources_$0-79",
                                "targetNames":"prototype"
                        }
                },
                "wc_operation_logs":{
                        "createTableSQL":"......",
                        "funcation":{
                                "clazz":"io.mycat.router.mycat1xfunction.PartitionByMod",
                                "properties":{
                                        "count":"100",
                                        "columnName":"id"
                                },
                                "ranges":{}
                        },
                        "partition":{
                                "schemaNames":"mycat2db",
                                "tableNames":"wc_operation_logs_$0-99",
                                "targetNames":"prototype"
                        }
                }
}

报错如下：
Exception in thread "main" io.mycat.MycatException: ERROR-CODE: [MYCAT-3036][ERR_INIT_CONFIG] start FileMetadataStorageManager fail
        at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
        at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:211)
        at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:204)
        at io.mycat.MycatCore.start(MycatCore.java:222)
        at io.mycat.MycatCore.main(MycatCore.java:235)
Caused by: io.mycat.MycatException: ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
        at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
        at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:133)
        at io.mycat.config.ConfigPrepareExecuter.fullInitBy(ConfigPrepareExecuter.java:209)
        at io.mycat.config.ConfigPrepareExecuter.prepareRuntimeObject(ConfigPrepareExecuter.java:133)
        at io.mycat.config.FileMetadataStorageManager.commitAndSyncDisk(FileMetadataStorageManager.java:271)
        at io.mycat.config.FileMetadataStorageManager$1.commit(FileMetadataStorageManager.java:250)
        at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:209)
        ... 3 more
Caused by: java.lang.NullPointerException
        at io.mycat.router.mycat1xfunction.PartitionRuleFunctionManager.getRuleAlgorithm(PartitionRuleFunctionManager.java:42)
        at io.mycat.MetadataManager.createShardingTable(MetadataManager.java:488)
        at io.mycat.MetadataManager.addShardingTable(MetadataManager.java:461)
        at io.mycat.MetadataManager.<init>(MetadataManager.java:259)
        at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:126)
        ... 8 more

**Comment by mkerj** [comment]
@mkerj 您可以拉我进群吗？我的QQ号是:6042771 谢谢！

**Comment by zwyqz** [comment]
> @mkerj 您可以拉我进群吗？我的QQ号是:6042771 谢谢！

加我扣扣1019100252 我拉你入群

**Comment by junwen12221** [comment]
"wc_operation_logs":{
"createTableSQL":"......",
"funcation":{
"clazz":"io.mycat.router.mycat1xfunction.PartitionByMod",
"properties":{
"count":"100",
"columnName":"id"
},

funcation拼写错误
