### ISSUE TITLE
使用datagrip连接时报错

### ISSUE THREAD

**Issue by t291436520** [MyCATApache/Mycat2#561]
分支master 
连接mysql 
在使用datagrip连接mycat2，时报At line 0, column 0: Column 'lower_case_table_names' not found in any table，经查证发现使用的sql 为
`SELECT lower_case_table_names AS lower_case_table_names;`
具体错误信息
`[pool-2-thread-6] DEBUG io.mycat.commands.MycatdbCommand - /* ApplicationName=DataGrip 2021.1.3 */ select @@GLOBAL.lower_case_table_names
[pool-2-thread-6] ERROR org.apache.calcite.runtime.CalciteException - org.apache.calcite.sql.validate.SqlValidatorException: Column 'lower_case_table_names' not found in any table
[pool-2-thread-6] ERROR org.apache.calcite.runtime.CalciteException - org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: Column 'lower_case_table_names' not found in any table
[pool-2-thread-6] ERROR io.mycat.sqlhandler.ShardingSQLHandler - /* ApplicationName=DataGrip 2021.1.3 */
SELECT @@global.lower_case_table_names
org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: Column 'lower_case_table_names' not found in any table
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:886)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:871)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5004)
	at org.apache.calcite.sql.validate.DelegatingScope.fullyQualify(DelegatingScope.java:259)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5900)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$SelectExpander.visit(SqlValidatorImpl.java:6063)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$SelectExpander.visit(SqlValidatorImpl.java:6049)
	at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:320)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101)
	at org.apache.calcite.sql.SqlAsOperator.acceptCall(SqlAsOperator.java:121)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5918)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectExpr(SqlValidatorImpl.java:5485)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:408)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4166)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3435)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1064)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1038)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1013)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:721)
	at io.mycat.DrdsSqlCompiler.getRelRoot(DrdsSqlCompiler.java:334)
	at io.mycat.DrdsSqlCompiler.compileQuery(DrdsSqlCompiler.java:278)
	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:167)
	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:159)
	at io.mycat.calcite.spm.MemPlanCache.add(MemPlanCache.java:182)
	at io.mycat.calcite.spm.QueryPlanner.getAcceptedMycatRelList(QueryPlanner.java:67)
	at io.mycat.calcite.spm.QueryPlanner.innerComputeMinCostCodeExecuterContext(QueryPlanner.java:28)
	at io.mycat.calcite.DrdsRunnerHelper.getPlan(DrdsRunnerHelper.java:349)
	at io.mycat.calcite.DrdsRunnerHelper.runOnDrds(DrdsRunnerHelper.java:337)
	at io.mycat.sqlhandler.ShardingSQLHandler.onExecute(ShardingSQLHandler.java:37)
	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
	at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:436)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:394)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:183)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:176)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:176)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:546)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:131)
	at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Column 'lower_case_table_names' not found in any table
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:560)
	... 61 more
[pool-2-thread-6] ERROR io.vertx.core.impl.future.FutureImpl - `

**Comment by junwen12221** [comment]
主分支是main分支,不是master分支

**Comment by junwen12221** [comment]
main分支已经修复这个问题

**Comment by t291436520** [comment]
好的，还有一个问题就是用navicat的时候， 我用的root 账户访问的数据库。 但是在Navicat中实际只看得到mysql 自己的库， 自己的业务库没有访问，如果我增加一个相同的数据库名，那么才能看到数据库信息，但是访问表数据的时候却报错，该库找不到对应的表

**Comment by t291436520** [comment]
使用datagrip的时候也是会有这个问题， 能显示出来全部库，但是点击某一个业务库的时候就报找不到表

**Comment by junwen12221** [comment]
mysql库是mycat内置默认配置的库,它在mycat里面是总是存在的,业务库不是默认配置的,需要自行配置

https://www.yuque.com/ccazhw/ml3nkf/00d1d4fc145edf34b2d13fcd95908722
https://www.yuque.com/ccazhw/ml3nkf/f9f24306bbd3992c1baff00cdb0956a4
https://www.yuque.com/ccazhw/ml3nkf/fb2285b811138a442eb850f0127d7ea3
![image](https://user-images.githubusercontent.com/11361391/126946003-62e8b438-3511-41c8-a509-21979d7af9b9.png)

**Comment by junwen12221** [comment]
![image](https://user-images.githubusercontent.com/11361391/126946164-8a7f1db1-208f-4b94-ae48-96a09d73e35c.png)

**Comment by t291436520** [comment]
好的多谢了 
不好意思， 没有仔细看文档
