### ISSUE TITLE
疑似创建分表失败

### ISSUE THREAD

**Issue by vitalQ** [MyCATApache/Mycat2#563]
mycat版本：1.19  http://dl.mycat.org.cn/2.0/1.19-release/mycat2-1.19-jar-with-dependencies.jar
schema文件：larp_social_0.schema.json
larp_social_0.schema.json：

> {
>         "customTables":{},
>         "globalTables":{},
>         "normalTables":{},
>         "schemaName":"larp_social_0",
>         "shadingTables":{}
> }

我是在mycat中执行SQL创建了数据库，数据库名叫 larp_social_0 ，然后通过注释方式创建分片表：

> /*+ mycat:createTable{
> 	"schemaName": "larp_social_0",
> 	"tableName": "topic",
> 	"shadingTables": {
> 		"createTableSQL": "CREATE TABLE `topic` ( `id` varchar(21) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, `create_time` datetime NOT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;",
> 		"function": {
> 			"properties": {
> 				"clazz": "io.mycat.router.mycat1xfunction.PartitionByPrefixPattern",
> 				"patternValue": 32,
> 				"prefixLength": 13,
> 				"columnName": "id",
> 				"defaultNode" : 0
> 			}
> 		},
> 		"partition": {
> 			"targetNames": "prototype",
> 			"schemaNames": "larp_social_0",
> 			"tableNames": "topic_$0-31"
> 		},
> 		"ranges": {
> 			"0-31": 0
> 		}
> 	}
> }
> */

执行没有提示错误，但是通过注释查看表的时候没有数据：

` /*+ mycat:showTables{"schemaName":"larp_social_0"}*/
`
然后尝试执行insert语句：

` INSERT INTO `topic` (`id`, `name`, `create_time`) VALUES ('162738683795300000001', '靓仔', '2021-07-22 11:47:46');
`

提示报错

`[pool-2-thread-9] ERROR io.mycat.MycatDataContext -
io.mycat.MycatException: Unable to route:INSERT INTO `topic` (`id`, `name`, `create_time`)
VALUES ('162738683795300000001', '靓仔', '2021-07-22 11:47:46')
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:80)
        at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
        at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
        at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:436)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:394)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:183)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:176)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:176)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:546)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:131)
        at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[pool-2-thread-9] ERROR io.vertx.core.impl.future.FutureImpl -
java.lang.RuntimeException: io.mycat.MycatException: Unable to route:INSERT INTO `topic` (`id`, `name`, `create_time`)
VALUES ('162738683795300000001', '靓仔', '2021-07-22 11:47:46')
        at io.mycat.commands.ReceiverImpl.sendError(ReceiverImpl.java:66)
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:80)
        at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
        at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
        at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:436)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:394)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:183)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:176)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:176)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:546)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:131)
        at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.mycat.MycatException: Unable to route:INSERT INTO `topic` (`id`, `name`, `create_time`)
VALUES ('162738683795300000001', '靓仔', '2021-07-22 11:47:46')
        ... 27 more`

通过`/*+ mycat:showUsers */`查看用户是有数据的

请问是不是我创建表没有成功，但是为何没有提示错误呢

**Comment by vitalQ** [comment]
我看了关于注释的文档，发现通过注释创建表不会创建物理表，于是我直接修改配置
```

{
        "customTables":{},
        "globalTables":{},
        "normalTables":{},
        "schemaName":"larp_social_0",
        "shadingTables":{

                "topic": {
                        "createTableSQL": "CREATE TABLE larp_social_0.`topic` ( `id` varchar(21) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, `create_time` datetime NOT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;",
                        "function": {
                                "properties": {
                                        "clazz": "io.mycat.router.mycat1xfunction.PartitionByPrefixPattern",
                                        "patternValue": 32,
                                        "prefixLength": 13,
                                        "columnName": "id",
                                        "storeNum" : 1
                                }
                        },
                        "partition": {
                                "targetNames": "prototype",
                                "schemaNames": "larp_social_0",
                                "tableNames": "topic_$0-31"
                        },
                        "ranges": {
                                "0-31": 0
                        }
                }
        }
}
```

重启mycat后，我试着查询数据
`select * from topic;`
返回空数据，说明表应该存在，但是我在物理库上没有看到任何一张表

然后我执行建表语句
`
CREATE TABLE `topic` (
  `id` varchar(21) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
`

创建了33张表，一张表是topic，剩余的都是topic_0-31，然后我尝试插入数据，结果报错了
`INSERT INTO `topic` (`id`, `name`, `create_time`) VALUES ('162738683795300000001', '靓仔', '2021-07-22 11:47:46');`

`
[pool-2-thread-8] ERROR io.vertx.core.impl.future.FutureImpl -
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at io.mycat.commands.MycatMySQLManagerImpl.getConnection(MycatMySQLManagerImpl.java:75)
        at cn.mycat.vertx.xa.impl.LocalSqlConnection.getConnection(LocalSqlConnection.java:78)
        at io.mycat.vertx.VertxExecuter.runMycatInsertRel(VertxExecuter.java:67)
        at io.mycat.calcite.plan.ObservablePlanImplementorImpl.innerExecuteInsert(ObservablePlanImplementorImpl.java:72)
        at io.mycat.calcite.plan.ObservablePlanImplementorImpl.executeInsert(ObservablePlanImplementorImpl.java:66)
        at io.mycat.calcite.DrdsRunnerHelper.impl(DrdsRunnerHelper.java:326)
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.executeUpdate(UpdateSQLHandler.java:117)
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:103)
        at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
        at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
        at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:436)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:394)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:183)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:176)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:176)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:546)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:131)
        at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[pool-2-thread-8] ERROR io.mycat.MycatDataContext -
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at io.mycat.commands.MycatMySQLManagerImpl.getConnection(MycatMySQLManagerImpl.java:75)
        at cn.mycat.vertx.xa.impl.LocalSqlConnection.getConnection(LocalSqlConnection.java:78)
        at io.mycat.vertx.VertxExecuter.runMycatInsertRel(VertxExecuter.java:67)
        at io.mycat.calcite.plan.ObservablePlanImplementorImpl.innerExecuteInsert(ObservablePlanImplementorImpl.java:72)
        at io.mycat.calcite.plan.ObservablePlanImplementorImpl.executeInsert(ObservablePlanImplementorImpl.java:66)
        at io.mycat.calcite.DrdsRunnerHelper.impl(DrdsRunnerHelper.java:326)
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.executeUpdate(UpdateSQLHandler.java:117)
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:103)
        at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
        at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
        at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:436)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:394)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:183)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:176)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:176)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:546)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:131)
        at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

所以问题是出现在哪里呢
