### ISSUE TITLE
用PartitionByHotDate单库分表插入数据报错

### ISSUE THREAD

**Issue by liu-arvin** [MyCATApache/Mycat2#565]
分表需求：单库根据create_time字段的值，实现每30天分一个历史表。

执行步骤：
```
mysql> /*+ mycat:resetConfig{} */;
mysql> create database db1;
mysql> /*+ mycat:createTable{
  "schemaName":"db1",
  "shadingTable":{
    "createTableSQL":"CREATE TABLE db1.`sharding` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` varchar(100) DEFAULT NULL,\n  `create_time` date DEFAULT NULL,\n  `fee` decimal(10,0) DEFAULT NULL,\n  `days` int DEFAULT NULL,\n  `blob` longblob,\n  PRIMARY KEY (`id`),\n  KEY `id` (`id`)\n) ENGINE=InnoDB  DEFAULT CHARSET=utf8",
    "function":{
      "clazz":"io.mycat.router.mycat1xfunction.PartitionByHotDate",
      "properties":{
        "dateFormat":"yyyy-MM-dd",
        "lastTime":30,
        "partionDay":30,
        "columnName":"create_time"
      }
    },
    "partition":{
      "schemaNames":"db1",
      "tableNames":"sharding_$0-2",
      "targetNames":"prototype"
    }
  },
  "tableName":"sharding"
} */;

```
mysql> use db1;
mysql> show tables;
+---------------+
| Tables_in_db1 |
+---------------+
| sharding      |
| sharding_0    |
| sharding_1    |
| sharding_2    |
+---------------+
4 rows in set (0.02 sec)

mysql> INSERT INTO `sharding` VALUES (null, 'test1', '2021-08-09', 2, 3, NULL);
插入数据的时候报错如下：
[pool-2-thread-8] ERROR io.mycat.MycatDataContext -
java.lang.IllegalArgumentException: 路由计算返回结果个数为3
        at io.mycat.router.CustomRuleFunction.calculateOne(CustomRuleFunction.java:46)
        at io.mycat.vertx.VertxExecuter.lambda$explainInsert$12(VertxExecuter.java:426)
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.util.Collections$2.tryAdvance(Unknown Source)
        at java.util.Collections$2.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at io.mycat.vertx.VertxExecuter.explainInsert(VertxExecuter.java:456)
        at io.mycat.calcite.plan.ObservablePlanImplementorImpl.executeInsert(ObservablePlanImplementorImpl.java:79)
        at io.mycat.calcite.DrdsRunnerHelper.impl(DrdsRunnerHelper.java:330)
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.executeUpdate(UpdateSQLHandler.java:117)
        at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:103)
        at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
        at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
        at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:436)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:164)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:394)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:183)
        at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:176)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
        at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
        at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
        at io.vertx.core.Future.compose(Future.java:199)
        at io.vertx.core.Future.flatMap(Future.java:180)
        at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:176)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:546)
        at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:131)
        at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by liu-arvin** [comment]
mysql> /*+ mycat:showTopology{
    ->   "schemaName":"db1",
    ->   "tableName":"sharding"
    -> } */;
+------------+------------+------------+
| targetName | schemaName | tableName  |
+------------+------------+------------+
| prototype  | db1        | sharding_0 |
| prototype  | db1        | sharding_1 |
| prototype  | db1        | sharding_2 |
+------------+------------+------------+
3 rows in set (0.01 sec)

**Comment by junwen12221** [comment]
应该是column没有写全,试试


```

INSERT INTO `db1`.`sharding`
 (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`)
 VALUES (NULL, 'test1', '2021-08-09', 2, 3, NULL);
```

**Comment by liu-arvin** [comment]
的确是因为column没有写全的问题，但是我插入多条数据后发现并没有分表储存是为什么呢？
INSERT INTO `db1`.`sharding` (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`) VALUES (NULL, 'test1', '2021-08-09', 2, 3, NULL);
INSERT INTO `db1`.`sharding` (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`) VALUES (NULL, 'test2', '2021-08-10', 2, 3, NULL);
INSERT INTO `db1`.`sharding` (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`) VALUES (NULL, 'test3', '2021-09-12', 2, 3, NULL);
INSERT INTO `db1`.`sharding` (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`) VALUES (NULL, 'test4', '2021-11-12', 2, 3, NULL);
INSERT INTO `db1`.`sharding` (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`) VALUES (NULL, 'test5', '2021-12-12', 2, 3, NULL);
然后这5条数据全部在sharding_0这个表里存储，这个是为什么？

**Comment by liu-arvin** [comment]
> 应该是column没有写全,试试
> 
> ```
> 
> INSERT INTO `db1`.`sharding`
>  (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`)
>  VALUES (NULL, 'test1', '2021-08-09', 2, 3, NULL);
> ```
是的


> 应该是column没有写全,试试
> 
> ```
> 
> INSERT INTO `db1`.`sharding`
>  (`id`, `user_id`, `create_time`, `fee`, `days`, `blob`)
>  VALUES (NULL, 'test1', '2021-08-09', 2, 3, NULL);
> ```
的确是因为column没有写全的问题，但是我插入多条数据后发现并没有分表储存是为什么呢？
INSERT INTO db1.sharding (id, user_id, create_time, fee, days, blob) VALUES (NULL, 'test1', '2021-08-09', 2, 3, NULL);
INSERT INTO db1.sharding (id, user_id, create_time, fee, days, blob) VALUES (NULL, 'test2', '2021-08-10', 2, 3, NULL);
INSERT INTO db1.sharding (id, user_id, create_time, fee, days, blob) VALUES (NULL, 'test3', '2021-09-12', 2, 3, NULL);
INSERT INTO db1.sharding (id, user_id, create_time, fee, days, blob) VALUES (NULL, 'test4', '2021-11-12', 2, 3, NULL);
INSERT INTO db1.sharding (id, user_id, create_time, fee, days, blob) VALUES (NULL, 'test5', '2021-12-12', 2, 3, NULL);
然后这5条数据全部在sharding_0这个表里存储，这个是为什么？

**Comment by junwen12221** [comment]
https://blog.csdn.net/wwangchenyu/article/details/88421261
