### ISSUE TITLE
mycat2与seata结合使用提交事务返回无法找到table meta

### ISSUE THREAD

**Issue by andryzhu** [MyCATApache/Mycat2#590]
服务环境：
        seata版本v1.4.2
        mycat2: mycat2-install-template-1.20 + mycat2-1.20-jar-with-dependencies-2021-9-14.jar
        java version "1.8.0_301"
        后端mysql：8.0.23
        

java程序更新数据时返回如下错误：
### Cause: java.sql.SQLException: io.seata.common.exception.ShouldNeverHappenException: [xid:10.244.0.120:8091:8313826059569131585]get table meta failed, please check whether the table `bms_shop` exists.
; uncategorized SQLException; SQL state [null]; error code [0]; io.seata.common.exception.ShouldNeverHappenException: [xid:10.244.0.120:8091:8313826059569131585]get table meta failed, please check whether the table `bms_shop` exists.; nested exception is java.sql.

**Comment by junwen12221** [comment]
先试试
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-9-29.jar

但是估计还是有这个错的,因为mycat2返回的查询结果集的字段信息不带有物理表的库名的表名,这个错要下一个版本才可以处理

**Comment by junwen12221** [comment]
可以改动seata源码,不通过mycat的连接查询原型库获取表信息,补上这个字段信息

**Comment by andryzhu** [comment]
请问改动seata源码哪个类的哪个方法？

**Comment by junwen12221** [comment]
记得1.6和2都有这个错的,有些用户自行改了源码适配上了,具体哪个代码需要看为啥报错

**Comment by andryzhu** [comment]
感觉好像是数据源连接后端mysql协议兼容问题，
在1.6中采用native协议不会出现这个错误，使用jdbc协议则会。
在2.0中采用native协议时，数据源url参数按照1.6方式"url":"192.168.0.20:3310"配置时mycat2启动出现如下错误：
WrapperSimpleApp: Encountered an error running main: com.alibaba.fastjson.JSONException: set property error, io.mycat.config.DatasourceConfig#url
INFO   | jvm 1    | 2021/10/15 10:41:21 | com.alibaba.fastjson.JSONException: set property error, io.mycat.config.DatasourceConfig#url
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.deserializer.FieldDeserializer.setValue(FieldDeserializer.java:162)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:123)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1241)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:866)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1555)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_14_DatasourceConfig.deserialze(Unknown Source)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:687)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.JSON.parseObject(JSON.java:383)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.JSON.parseObject(JSON.java:287)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at com.alibaba.fastjson.JSON.parseObject(JSON.java:560)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at io.mycat.util.JsonUtil.from(JsonUtil.java:50)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at io.mycat.configreaderwriter.JsonConfigReaderWriter.transformation(JsonConfigReaderWriter.java:17)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at io.mycat.config.CoordinatorMetadataStorageManager.lambda$loadFromLocalConfigCenter$12(CoordinatorMetadataStorageManager.java:128)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at io.mycat.config.CoordinatorMetadataStorageManager.loadFromLocalConfigCenter(CoordinatorMetadataStorageManager.java:129)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at io.mycat.config.CoordinatorMetadataStorageManager.start(CoordinatorMetadataStorageManager.java:45)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at io.mycat.MycatCore.startServer(MycatCore.java:215)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at io.mycat.MycatCore.main(MycatCore.java:233)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2021/10/15 10:41:21 |       at java.lang.Thread.run(Thread.java:748)

**Comment by junwen12221** [comment]
是mysql协议兼容性问题,他这个问题是字段报文里面缺少表名信息导致的,要么在mycat2代码里面补上这个信息,要么在seata里面补上

这个分支上

https://github.com/MyCATApache/Mycat2/tree/2021-8-23-fix

io.mycat.beans.mysql.packet.ColumnDefPacketImpl#ColumnDefPacketImpl(io.mycat.beans.mycat.MycatRowMetaData, int)
```

  this.columnSchema = new byte[]{};
            String columnName = resultSetMetaData.getColumnName(columnIndex);
            this.columnName = getBytes(columnName);
            this.columnOrgName = new byte[]{};
            this.columnOrgTable = new byte[]{};
            this.columnTable = new byte[]{};
```

试试把columnSchema,columnOrgTable,columnTable改成对应的库名,表名.

seata获取字段的属性不对就会报错,在seata找到判断这个属性的代码改掉就可以,

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-10-15.jar
