### ISSUE TITLE
Mycat2 连接 postgresql或者opengauss问题，无法启动

### ISSUE THREAD

**Issue by Libao-Yang** [MyCATApache/Mycat2#603]
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | path:/usr/local/mycat/./conf
jvm 1    | 2021-11-06 07:43:26,376[INFO]io.mycat.MycatCore.newMycatServer:208start VertxMycatServer
jvm 1    | 2021-11-06 07:43:26,768[INFO]com.alibaba.druid.pool.DruidDataSource.init:990{dataSource-1} inited
jvm 1    | Nov 06, 2021 7:43:26 AM org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
jvm 1    | INFO: [030480b7-a218-4992-8b00-34b729c922bd] Try to connect. IP: 172.11.0.101:5432
jvm 1    | Nov 06, 2021 7:43:26 AM org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
jvm 1    | INFO: [172.11.0.2:50332/172.11.0.101:5432] Connection is established. ID: 030480b7-a218-4992-8b00-34b729c922bd
jvm 1    | Nov 06, 2021 7:43:26 AM org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
jvm 1    | INFO: Connect complete. ID: 030480b7-a218-4992-8b00-34b729c922bd
jvm 1    | Nov 06, 2021 7:43:26 AM org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
jvm 1    | INFO: [2a6fb1ce-b1b9-4807-a53c-9781e4d0f64f] Try to connect. IP: 172.11.0.101:5432
jvm 1    | 
jvm 1    | WrapperSimpleApp: Encountered an error running main: io.mycat.MycatException: ERROR-CODE: [MYCAT-3036][ERR_INIT_CONFIG] start FileMetadataStorageManager fail
jvm 1    | io.mycat.MycatException: ERROR-CODE: [MYCAT-3036][ERR_INIT_CONFIG] start FileMetadataStorageManager fail
jvm 1    |      at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
jvm 1    |      at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:211)
jvm 1    |      at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:204)
jvm 1    |      at io.mycat.MycatCore.startServer(MycatCore.java:215)
jvm 1    |      at io.mycat.MycatCore.main(MycatCore.java:233)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    |      at java.lang.reflect.Method.invoke(Method.java:498)
jvm 1    |      at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
jvm 1    |      at java.lang.Thread.run(Thread.java:748)
jvm 1    | Caused by: io.mycat.MycatException: ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
jvm 1    |      at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
jvm 1    |      at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:131)
jvm 1    |      at io.mycat.config.ConfigPrepareExecuter.fullInitBy(ConfigPrepareExecuter.java:217)
jvm 1    |      at io.mycat.config.ConfigPrepareExecuter.prepareRuntimeObject(ConfigPrepareExecuter.java:135)
jvm 1    |      at io.mycat.config.FileMetadataStorageManager.commitAndSyncDisk(FileMetadataStorageManager.java:271)
jvm 1    |      at io.mycat.config.FileMetadataStorageManager$1.commit(FileMetadataStorageManager.java:250)
jvm 1    |      at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:209)
jvm 1    |      ... 9 more
jvm 1    | Caused by: io.mycat.MycatException: org.postgresql.util.PSQLException: [172.11.0.2:50332/172.11.0.101:5432] ERROR: syntax error at or near "VARIABLES"
jvm 1    |   Position: 14
jvm 1    |      at io.mycat.datasource.jdbc.datasource.DefaultConnection.executeQuery(DefaultConnection.java:93)
jvm 1    |      at io.mycat.MetadataManager.<init>(MetadataManager.java:166)
jvm 1    |      at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:124)
jvm 1    |      ... 14 more
jvm 1    | Caused by: org.postgresql.util.PSQLException: [172.11.0.2:50332/172.11.0.101:5432] ERROR: syntax error at or near "VARIABLES"
jvm 1    |   Position: 14
jvm 1    |      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2820)
jvm 1    |      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2550)
jvm 1    |      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:329)
jvm 1    |      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:453)
jvm 1    |      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:377)
jvm 1    |      at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:319)
jvm 1    |      at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:305)
jvm 1    |      at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:282)
jvm 1    |      at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
jvm 1    |      at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:296)
jvm 1    |      at io.mycat.datasource.jdbc.datasource.DefaultConnection.executeQuery(DefaultConnection.java:84)
jvm 1    |      ... 16 more
jvm 1    | 2021-11-06 07:43:26,920[INFO]io.mycat.replica.heartbeat.HeartbeatFlow.sendDataSourceStatus:66prototypeDs heartStatus DatasourceStatus(status=OK_STATUS, isSlaveBehindMaster=false, dbSynStatus=DB_SYN_NORMAL, master=true)
jvm 1    | Nov 06, 2021 7:43:26 AM org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
jvm 1    | INFO: [172.11.0.2:50334/172.11.0.101:5432] Connection is established. ID: 2a6fb1ce-b1b9-4807-a53c-9781e4d0f64f
jvm 1    | Nov 06, 2021 7:43:26 AM org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
jvm 1    | INFO: Connect complete. ID: 2a6fb1ce-b1b9-4807-a53c-9781e4d0f64f
wrapper  | <-- Wrapper Stopped

**Comment by junwen12221** [comment]
暂时不支持pg

**Comment by junwen12221** [comment]
mycat需要一个mysql作为配置中心,作为原型库,而存储节点可以是pg

**Comment by wangjianme** [comment]
> 

为了做为pg的中间件，还需要一个额外的mysql做为原型库，真是多余的设计！！！

**Comment by zwyqz** [comment]
> > 
> 
> 为了做为pg的中间件，还需要一个额外的mysql做为原型库，真是多余的设计！！！

用不用请自行评估；当然欢迎你给社区做贡献，或者提出更好的设计，以及贡献代码；
