### ISSUE TITLE
order by 导致mycat崩溃

### ISSUE THREAD

**Issue by wangsenyan** [MyCATApache/Mycat2#609]
SELECT `id`,`name`,`description`,`projectid`,`masterid`,`appid`,`user`,`userid`,`tag`,`ct`,`ut`,`deleted` FROM `tag` WHERE `masterid`= 33538260487639040 ORDER BY `ct` DESC;

这只有一条数据，没有order by 很快就返回,加上order by，会令mycat退出
JVM exited unexpectedly.
JVM exited in response to signal SIGKILL (9).
 Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

我的配置,2个cluster,每个一数据库一表

**Comment by junwen12221** [comment]
估计是内存不够了或者被内存限制等因素被杀死了
加上limit 1000看看

JVM参数加上
-XX:+HeapDumpBeforeFullGC 
-XX:HeapDumpPath=xxxx/xxx
在wrapper.conf里面可以配置

可以得到异常信息

mycat日志可以设置debug级别

**Comment by junwen12221** [comment]
是被外部命令kill -9杀死jvm的

**Comment by junwen12221** [comment]
可以尝试直接使用jar包启动,不使用java wrapper service

**Comment by junwen12221** [comment]
order这边是有测试样例的,但是没有复现这个问题

**Comment by wangsenyan** [comment]
配置文件，2 cluster，每个cluster 1 个db, 每个db 1个tb
  "tag": {
      "function": {
        "properties": {
          "mappingFormat": "c${dbIndex}/biz_design_custom/tag",
          "dbNum": 2,
          "tableNum": 1,
          "tableMethod": "mod_hash(projectid)",
          "storeNum": 2,
          "dbMethod": "mod_hash(projectid)"
        }
      }
    },
使用java -DMYCAT_HOME=mycat\conf -jar mycat2-1.20-jar-with-dependencies.jar 启动
只有一条数据，不加order by正常返回，加上后就一直执行
最后报错：
```sh
SELECT id, name, description, projectid, masterid
        , appid, user, userid, tag, `ct`
        , ut, deleted
FROM `biz_design_custom`.tag
WHERE masterid = 33538260487639040
ORDER BY id DESC
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.calcite.util.Util.transform(Util.java:2576)
        at org.apache.calcite.rel.core.Sort.getSortExps(Sort.java:172)
        at org.apache.calcite.rel.core.Sort.explainTerms(Sort.java:182)
        at org.apache.calcite.rel.AbstractRelNode.getDigestItems(AbstractRelNode.java:409)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:391)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:398)
[WARN]com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal:1494discard long time none received connection. , jdbcUrl : jdbc:mysql://ip:port/mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true, version : 1.2.5, lastPacketReceivedIdleMillis : 102782
```
怀疑是因为只有一条数据的问题，因为用其他表，每个表都有数据，order by会返回

**Comment by junwen12221** [comment]
知道这个问题了,优化器死循环了

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-12-2.jar

这个包没有解决问题,但是会输出错误死循环的地方

另外设置日志为debug模式,会输出构建执行计划的日志
https://www.yuque.com/ccazhw/ml3nkf/1faac0f0187f3dda0acfbeeb9cc6656c

explain SELECT id,name,description,projectid,masterid,appid,user,userid,tag,ct,ut,deleted FROM tag WHERE masterid= 33538260487639040 ORDER BY ct DESC;

可以触发构建执行计划

估计会观察到构造到了一个父子节点都是相同的节点的执行计划

另外需要这个表的建表语句,可能它有点特殊,会触发这个bug

**Comment by wangsenyan** [comment]
这是建表语句
```sql
CREATE TABLE `tag` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `projectid` bigint(20) DEFAULT NULL,
  `masterid` bigint(20) DEFAULT NULL,
  `appid` varchar(255) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `tag` varchar(255) DEFAULT NULL,
  `ct` datetime(6) DEFAULT NULL,
  `ut` datetime(6) DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT NULL,
  `userid` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
错误
```sh
SELECT id, name, description, `projectid`, `masterid`
        , `appid`, `user`, `userid`, `ct`, `ut`
        , deleted
FROM `biz_design_custom`.tag
WHERE masterid = 33538260487639040
ORDER BY id DESC
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.calcite.linq4j.Ord.of(Ord.java:49)
        at org.apache.calcite.linq4j.Ord$OrdList.get(Ord.java:189)
        at org.apache.calcite.linq4j.Ord$OrdList.get(Ord.java:181)
        at java.util.AbstractList$Itr.next(Unknown Source)
        at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:70)
        at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:141)
        at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:219)
        at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:57)
        at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:71)
        at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:141)
        at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:219)
        at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:57)
        at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:71)
        at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:141)
        at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:219)
        at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:57)
        at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:71)
        at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:141)
        at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:219)
        at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:57)
        at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:71)
        at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:141)
        at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:219)
        at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:57)
        at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:71)
        at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:141)
        at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:219)
        at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:57)
        at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:71)
        at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:141)
        at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:219)
        at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:57)
```

另一条带order的日志
```sh
Exception in thread "vertx-blocked-thread-checker" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.Throwable.getStackTraceElement(Native Method)
        at java.lang.Throwable.getOurStackTrace(Unknown Source)
        at java.lang.Throwable.getStackTrace(Unknown Source)
        at ch.qos.logback.classic.spi.CallerData.extract(CallerData.java:60)
        at ch.qos.logback.classic.spi.LoggingEvent.getCallerData(LoggingEvent.java:258)
        at ch.qos.logback.classic.pattern.MethodOfCallerConverter.convert(MethodOfCallerConverter.java:22)
        at ch.qos.logback.classic.pattern.MethodOfCallerConverter.convert(MethodOfCallerConverter.java:19)
        at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:36)
        at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:115)
        at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:141)
        at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:39)
        at ch.qos.logback.core.encoder.LayoutWrappingEncoder.encode(LayoutWrappingEncoder.java:115)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.log(Logger.java:765)
        at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:188)
        at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:160)
        at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:156)
        at io.vertx.core.logging.SLF4JLogDelegate.warn(SLF4JLogDelegate.java:86)
        at io.vertx.core.impl.logging.LoggerAdapter.warn(LoggerAdapter.java:79)
        at io.vertx.core.impl.BlockedThreadChecker$1.run(BlockedThreadChecker.java:59)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
2021-12-02 20:48:56,715[ERROR]io.mycat.sqlhandler.ShardingSQLHandler.onExecute:40-- SELECT * FROM `test` order by id;
SELECT id, name, description, `projectid`, `masterid`
        , `appid`, `user`, `userid`, `ct`, `ut`
        , deleted
FROM `biz_design_custom`.tag
ORDER BY id DESC
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.calcite.rel.core.Sort.explainTerms(Sort.java:183)
        at org.apache.calcite.rel.AbstractRelNode.getDigestItems(AbstractRelNode.java:416)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:393)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:404)
```

**Comment by wangsenyan** [comment]
我debug进去，看到类似getRowCount的这个返回了很大的值，有120万,不知道是不是和这个bug有关
我的两个表仅有不到600条数据

**Comment by junwen12221** [comment]
ide下debug能查询出数据吗,看上去你还没有设置好debug级别的日志

**Comment by junwen12221** [comment]
io.mycat.DrdsSqlCompiler#optimizeWithCBO 此处是需要定位的地方

**Comment by junwen12221** [comment]
io.mycat.calcite.rewriter.SQLRBORewriter#sort 是order完成改写的地方

**Comment by junwen12221** [comment]
`org.slf4j.simpleLogger.defaultLogLevel=debug
`
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>
				%d[%level]%c{100}.%M:%L%m%n
			</pattern>
		</encoder>
	</appender>

	<root level="debug">
		<appender-ref ref="CONSOLE" />
	</root>
</configuration>
```
设置日志级别,找到类似的日志
```

2021-12-02 23:59:11,750[DEBUG]org.apache.calcite.plan.RelOptPlanner.fireRule:319call#166: Apply rule [ProjectViewRule] to [rel#84:LogicalProject.NONE.[](input=HepRelVertex#83,inputs=0..1), rel#79:MycatView.MYCAT2.[](relNode=LocalTableScan#80,distribution=[db1.travelrecord])]
2021-12-02 23:59:11,753[DEBUG]org.apache.calcite.plan.RelOptPlanner.notifyTransformation:359call#166: Rule ProjectViewRule arguments [rel#84:LogicalProject.NONE.[](input=HepRelVertex#83,inputs=0..1), rel#79:MycatView.MYCAT2.[](relNode=LocalTableScan#80,distribution=[db1.travelrecord])] produced rel#90:MycatView.MYCAT2.[](relNode=LocalProject#92,distribution=[db1.travelrecord])
2021-12-02 23:59:11,757[DEBUG]org.apache.calcite.plan.RelOptPlanner.fireRule:319call#167: Apply rule [SortViewRule] to [rel#86:LogicalSort.NONE.[0](input=HepRelVertex#93,sort0=$0,dir0=ASC), rel#90:MycatView.MYCAT2.[](relNode=LocalProject#92,distribution=[db1.travelrecord])]
2021-12-02 23:59:11,759[DEBUG]org.apache.calcite.plan.RelOptPlanner.notifyTransformation:359call#167: Rule SortViewRule arguments [rel#86:LogicalSort.NONE.[0](input=HepRelVertex#93,sort0=$0,dir0=ASC), rel#90:MycatView.MYCAT2.[](relNode=LocalProject#92,distribution=[db1.travelrecord])] produced rel#97:MycatView.MYCAT2.[0](relNode=LocalSort#100,distribution=[db1.travelrecord],mergeSort=true)
2021-12-02 23:59:11,759[DEBUG]org.apache.calcite.plan.AbstractRelOptPlanner.rule_execution_summary.dumpRuleAttemptsInfo:290Rule Attempts Info for HepPlanner
2021-12-02 23:59:11,760[DEBUG]org.apache.calcite.plan.AbstractRelOptPlanner.rule_execution_summary.dumpRuleAttemptsInfo:291
Rules                                                                   Attempts           Time (us)
ReduceExpressionsRule(Project)                                                 1              23,307
ProjectViewRule                                                                1               2,925
SortViewRule                                                                   1               1,502
* Total                                                                        3              27,734

2021-12-02 23:59:11,760[DEBUG]org.apache.calcite.plan.RelOptPlanner.notifyChosen:381For final plan, using rel#97:MycatView.MYCAT2.[0](relNode=LocalSort#100,distribution=[db1.travelrecord],mergeSort=true)
2021-12-02 23:59:11,817[DEBUG]io.mycat.DrdsExecutorCompiler.getCodeExecuterContext:315----------------------------------------code----------------------------------------
2021-12-02 23:59:11,818[DEBUG]io.mycat.DrdsExecutorCompiler.getCodeExecuterContext:316public Object bindObservable(final org.apache.calcite.runtime.NewMycatDataContext root) {
  return root.getObservable("MycatView.MYCAT2.[0](relNode=LocalSort#100,distribution=[db1.travelrecord],mergeSort=true)", new org.apache.calcite.linq4j.function.Function1() {
      public long apply(Object[] v) {
```

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-12-3.jar

这个bug比较固定还是必现的,是重复下推的bug

https://github.com/MyCATApache/Mycat2/commit/579ec4a3aec919a7552e80048dd958684a4c40b9

**Comment by wangsenyan** [comment]
我用了您提供的最新jar包，再次查询没有问题了，十分感谢
