### ISSUE TITLE
使用sysbench做性能测试mycat创建表时报 “can not get lock :DDL_LOCK”

### ISSUE THREAD

**Issue by anson88616425** [MyCATApache/Mycat2#631]
使用sysbench测试：
创建16张表，每张表插入10000000条数据
sysbench oltp_common \
    --threads=16 \
    --rand-type=uniform \
    --db-driver=mysql \
    --mysql-db=testdb \
    --mysql-host=192.168.1.27 \
    --mysql-port=3307 \
    --mysql-user=root \
    --mysql-password=password \
    prepare --tables=16 --table-size=10000000
报错信息：
Initializing worker threads...

Creating table 'sbtest7'...
Creating table 'sbtest12'...
Creating table 'sbtest2'...
Creating table 'sbtest11'...
Creating table 'sbtest8'...
Creating table 'sbtest14'...
Creating table 'sbtest16'...
Creating table 'sbtest5'...
Creating table 'sbtest1'...
Creating table 'sbtest13'...
Creating table 'sbtest3'...
Creating table 'sbtest10'...
Creating table 'sbtest4'...
Creating table 'sbtest9'...
Creating table 'sbtest15'...
Creating table 'sbtest6'...
Inserting 10000000 records into 'sbtest12'
Inserting 10000000 records into 'sbtest2'
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest1(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest5(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
(last message repeated 1 times)
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest14(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest13(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest10(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest4(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest16(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest3(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
(last message repeated 3 times)
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest9(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest11(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest15(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest8(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE TABLE sbtest6(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:197: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
Inserting 10000000 records into 'sbtest7'
Creating a secondary index on 'sbtest7'...
Creating a secondary index on 'sbtest12'...
Creating a secondary index on 'sbtest2'...
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE INDEX k_12 ON sbtest12(k)'
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:238: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 1105 (can not get lock :DDL_LOCK) for query 'CREATE INDEX k_2 ON sbtest2(k)'
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:238: SQL error, errno = 1105, state = 'HY000': can not get lock :DDL_LOCK
FATAL: mysql_drv_query() returned error 0 (Future{cause=io.mycat.MycatException: com.mysql.cj.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request}) for query 'CREATE INDEX k_7 ON sbtest7(k)'
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:238: SQL error, errno = 0, state = 'HY000': Future{cause=io.mycat.MycatException: com.mysql.cj.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request}

**Comment by junwen12221** [comment]
这个问题是已知的,先给一个尝试修复的测试版给你

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/test/mycat2-1.21-release-jar-with-dependencies-test.jar

**Comment by anson88616425** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/test/mycat2-1.21-release-jar-with-dependencies-test.jar
已经更新jar包，第一次执行没有报错。第二次执行报这个错，有两个表没有创建成功。
![image](https://user-images.githubusercontent.com/11780232/147555080-8a063002-1cd9-478f-a8fc-12b7b726ce84.png)

**Comment by junwen12221** [comment]
你把测试脚本,工具给我看看,这ddl执行是有可能失败,比较难解决

**Comment by junwen12221** [comment]
最好能找到失败的原因

**Comment by junwen12221** [comment]
mycat日志看看有没有异常

**Comment by anson88616425** [comment]
> 最好能找到失败的原因



> 你把测试脚本,工具给我看看,这ddl执行是有可能失败,比较难解决
sysbench 这个是测试工具
sysbench oltp_common
--threads=16
--rand-type=uniform
--db-driver=mysql
--mysql-db=testdb
--mysql-host=192.168.1.27
--mysql-port=3307
--mysql-user=root
--mysql-password=password
prepare --tables=16 --table-size=10000000

**Comment by anson88616425** [comment]
> mycat日志看看有没有异常

mycat日志没有创建表的语句，创建成功的表的日志也没有。
INFO   | jvm 1    | 2021/12/28 17:43:14 | 2021-12-28 17:43:14,052[ERROR]io.vertx.core.impl.future.FutureImpl.?:?tryFail
INFO   | jvm 1    | 2021/12/28 17:43:14 | java.sql.SQLSyntaxErrorException: Table 'testdb.sbtest10' doesn't exist
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at io.mycat.newquery.NewMycatConnectionImpl.insert(NewMycatConnectionImpl.java:301)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$insert$2(ThreadMycatConnectionImplWrapper.java:74)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:33)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 2021-12-28 17:43:14,052[ERROR]io.vertx.core.impl.future.FutureImpl.?:?tryFail
INFO   | jvm 1    | 2021/12/28 17:43:14 | java.sql.SQLSyntaxErrorException: Table 'testdb.sbtest10' doesn't exist
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at io.mycat.newquery.NewMycatConnectionImpl.insert(NewMycatConnectionImpl.java:301)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$insert$2(ThreadMycatConnectionImplWrapper.java:74)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:33)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2021/12/28 17:43:14 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by junwen12221** [comment]
更改jar包里面的日志配置,才可以显示日志

**Comment by junwen12221** [comment]
这个建表语句应该是并发执行的

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/test/mycat2-1.21-release-jar-with-dependencies-test.jar

测试时候,先更改jar里面的日志级别

**Comment by anson88616425** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/test/mycat2-1.21-release-jar-with-dependencies-test.jar
> 
> 测试时候,先更改jar里面的日志级别

测试脚本：
`sysbench oltp_point_select \
    --threads=150 \
    --time=300 \
    --report-interval=1 \
    --rand-type=uniform \
    --db-driver=mysql \
    --mysql-db=testdb \
    --mysql-host=0.0.0.0 \
    --mysql-port=8077 \
    --mysql-user=user \
    --mysql-password=pwd \
    run --tables=16 --table-size=10000000`

sysbench日志报错：
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

FATAL: mysql_stmt_execute() returned error 0 () for query 'SELECT c FROM sbtest11 WHERE id=?'
FATAL: mysql_stmt_execute() returned error 0 () for query 'SELECT c FROM sbtest2 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:419: SQL error, errno = 0, state = '00000': 
(last message repeated 1 times)
FATAL: mysql_stmt_execute() returned error 0 () for query 'SELECT c FROM sbtest3 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:419: SQL error, errno = 0, state = '00000': ``

mycat日志：
`
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,843[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest6 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,843[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest13 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,843[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest13 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,843[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest13 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,863[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest13 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,870[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest11 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,871[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest11 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,874[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest9 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,880[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest6 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,880[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest14 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,880[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest14 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,880[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest14 WHERE id=?
--
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,945[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest16 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,946[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest16 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,946[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest14 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,946[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest14 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,954[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest8 WHERE id=?
INFO   | jvm 1    | 2021/12/29 09:59:02 | 2021-12-29 09:59:02,955[DEBUG]io.mycat.mycatmysql.MycatVertxMySQLHandler.handlePrepareStatement:487received pstmt sql:SELECT c FROM sbtest11 WHERE id=?
`

**Comment by junwen12221** [comment]
这里的异常信息
id=?' FATAL: thread_run' function failed: /usr/share/sysbench/oltp_common.lua:419: SQL error, errno = 0, state = '00000': ``
有没有更多信息?

可以试试多压测几次看看这个问题会不会复现,如果开启了读写分离,在进行一致性方面的检查的时候是会出错的.请把读写分离中的从节点去掉

**Comment by anson88616425** [comment]
> 

压测不到，开1个线程也报错，现在只是测试查询没有写的语句
FATAL: mysql_stmt_execute() returned error 0 () for query 'SELECT c FROM sbtest2 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:419: SQL error, errno = 0, state = '00000': 
Error in my_thread_global_end(): 1 threads didn't exit

**Comment by anson88616425** [comment]
> 这里的异常信息 id=?' FATAL: thread_run' function failed: /usr/share/sysbench/oltp_common.lua:419: SQL error, errno = 0, state = '00000': `` 有没有更多信息?
> 
> 可以试试多压测几次看看这个问题会不会复现,如果开启了读写分离,在进行一致性方面的检查的时候是会出错的.请把读写分离中的从节点去掉

有没其他压测工具推荐，可以压测mycat的。

**Comment by junwen12221** [comment]
只测查询的话,可以用这个看看

https://4399.feishu.cn/docs/doccnrPTgusNEN2pBqYK6nbkRyb?share_token=381d492d-4dfb-4165-b59d-e3f1677c8b51

**Comment by junwen12221** [comment]
最近比较多任务,这个问题得等有时间再处理

**Comment by junwen12221** [comment]
如果知道问题在哪里请第一时间告诉我

**Comment by anson88616425** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 晚上7:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MyCATApache/Mycat2] 使用sysbench做性能测试mycat创建表时报 “can not get lock :DDL_LOCK” (Issue #631)





 
如果知道问题在哪里请第一时间告诉我
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by junwen12221** [comment]
这个问题是测试的时候,测试的连接是并行执行建表语句,而mycat内部的锁失效了,导致一些建表配置没有生效导致的.

现在这个问题已经修复了.

http://dl.mycat.org.cn/2.0/1.21-release/test/mycat2-1.21-release-jar-with-dependencies-2021-12-30-test.jar

**Comment by anson88616425** [comment]
> 
这个问题应该是开启多线程不能查询多张表的问题。我查一张表就可以，测试脚本：
sysbench oltp_point_select \
    --threads=100 \
    --time=10 \
    --report-interval=1 \
    --rand-type=uniform \
    --db-driver=mysql \
    --mysql-db=testdb \
    --mysql-host=0.0.0.0 \
    --mysql-port=8077 \
    --mysql-user=donlimDev \
    --mysql-password=123 \
    run --tables=1--table-size=10000000


我"--tables=1"就可以,"--tables=16"就不行

**Comment by junwen12221** [comment]
报什么异常

ATAL: mysql_stmt_execute() returned error 0 () for query 'SELECT c FROM sbtest2 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:419: SQL error, errno = 0, state = '00000':
Error in my_thread_global_end(): 1 threads didn't exit
还是这样错误吗

**Comment by junwen12221** [comment]
这个问题,我这边已经复现了,是sysbench的客户端报文与服务端不兼容的问题

**Comment by junwen12221** [comment]
sysbench oltp_point_select  --mysql-host=127.0.0.1  --mysql-port=8066  --mysql-user=root  --mysql-password='123456'  --mysql-db=testdb  --db-driver=mysql  --tables=2  --table-size=1  --report-interval=1  --threads=1 --mysql-debug=on --db-ps-mode=disable run

添加--db-ps-mode=disable可以避免这个错误

**Comment by junwen12221** [comment]
对应jdbc禁用服务器预处理模式,此参数默认是关闭服务器预处理的

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/test/mycat2-1.21-release-jar-with-dependencies-2022-1-12-test-0.jar

**Comment by junwen12221** [comment]
这个bug已经修复

**Comment by wangjianme** [comment]
bug太多了，生产环境不敢用了。
