### ISSUE TITLE
nacos连接报错

### ISSUE THREAD

**Issue by li975732169** [MyCATApache/Mycat2#650]
2022-03-18T07:16:21.933483537Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.GeneratedConstructorAccessor30.newInstance(Unknown Source)
2022-03-18T07:16:21.933487354Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2022-03-18T07:16:21.933491178Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2022-03-18T07:16:21.933494823Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
2022-03-18T07:16:21.933498568Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:886)
2022-03-18T07:16:21.933502300Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:871)
2022-03-18T07:16:21.933507477Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5004)
2022-03-18T07:16:21.933512285Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:134)
2022-03-18T07:16:21.933516256Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:184)
2022-03-18T07:16:21.933520190Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
2022-03-18T07:16:21.933524033Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1064)
2022-03-18T07:16:21.933527726Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1038)
2022-03-18T07:16:21.933531486Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3166)
2022-03-18T07:16:21.933535242Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3148)
2022-03-18T07:16:21.933540283Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3422)
2022-03-18T07:16:21.933544870Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
2022-03-18T07:16:21.933548735Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
2022-03-18T07:16:21.933557930Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1064)
2022-03-18T07:16:21.933561944Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1038)
2022-03-18T07:16:21.933565771Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
2022-03-18T07:16:21.933569504Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1013)
2022-03-18T07:16:21.933573292Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:721)
2022-03-18T07:16:21.933578367Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.getRelRoot(DrdsSqlCompiler.java:396)
2022-03-18T07:16:21.933582817Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.compileQuery(DrdsSqlCompiler.java:330)
2022-03-18T07:16:21.933587117Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:219)
2022-03-18T07:16:21.933591015Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:211)
2022-03-18T07:16:21.933594545Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.spm.MemPlanCache.add(MemPlanCache.java:182)
2022-03-18T07:16:21.933597882Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.spm.QueryPlanner.getAcceptedMycatRelList(QueryPlanner.java:69)
2022-03-18T07:16:21.933601372Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.spm.QueryPlanner.innerComputeMinCostCodeExecuterContext(QueryPlanner.java:28)
2022-03-18T07:16:21.933604798Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.DrdsRunnerHelper.getPlan(DrdsRunnerHelper.java:370)
2022-03-18T07:16:21.933610014Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.DrdsRunnerHelper.runOnDrds(DrdsRunnerHelper.java:358)
2022-03-18T07:16:21.933615128Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.sqlhandler.ShardingSQLHandler.onExecute(ShardingSQLHandler.java:58)
2022-03-18T07:16:21.933619155Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
2022-03-18T07:16:21.933623030Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:481)
2022-03-18T07:16:21.933626762Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
2022-03-18T07:16:21.933630754Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
2022-03-18T07:16:21.933634558Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
2022-03-18T07:16:21.933638400Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
2022-03-18T07:16:21.933643798Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.compose(Future.java:199)
2022-03-18T07:16:21.933648690Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.flatMap(Future.java:180)
2022-03-18T07:16:21.933653404Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:446)
2022-03-18T07:16:21.933657542Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:200)
2022-03-18T07:16:21.933665306Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:196)
2022-03-18T07:16:21.933669373Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
2022-03-18T07:16:21.933673248Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
2022-03-18T07:16:21.933677112Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
2022-03-18T07:16:21.933682323Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
2022-03-18T07:16:21.933711296Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
2022-03-18T07:16:21.933716830Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.compose(Future.java:199)
2022-03-18T07:16:21.933720877Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.flatMap(Future.java:180)
2022-03-18T07:16:21.933724744Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:196)
2022-03-18T07:16:21.933728718Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:524)
2022-03-18T07:16:21.933732626Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:94)
2022-03-18T07:16:21.933737812Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
2022-03-18T07:16:21.933742722Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-03-18T07:16:21.933747032Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-03-18T07:16:21.933751047Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
2022-03-18T07:16:21.933754898Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'dual' not found within 'nacos_config'
2022-03-18T07:16:21.933758895Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
2022-03-18T07:16:21.933762740Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2022-03-18T07:16:21.933766919Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2022-03-18T07:16:21.933772107Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
2022-03-18T07:16:21.933776839Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:560)
2022-03-18T07:16:21.933780926Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	... 53 common frames omitted
2022-03-18T07:16:21.933785864Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 2022-03-18 07:16:21,887[INFO]io.mycat.vertx.VertxMycatServer.lambda$addSession$0:148session:io.mycat.mycatmysql.MycatVertxMysqlSession@4061b125 is closing
2022-03-18T07:16:21.933789963Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 2022-03-18 07:16:21,889[ERROR]io.mycat.DrdsSqlCompiler.getRelRoot:402sqlStatement:SELECT ? AS ?
2022-03-18T07:16:21.933793928Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | FROM `nacos_config`.dual sqlNode:SELECT ? AS `?`
2022-03-18T07:16:21.933801185Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | FROM `nacos_config`.`dual`
2022-03-18T07:16:21.933805040Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | /*+ `QB_NAME`(`dual`) */ validated:null root:null newRelNode:null
2022-03-18T07:16:21.933810468Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 2022-03-18 07:16:21,889[ERROR]io.mycat.sqlhandler.ShardingSQLHandler.onExecute:61SELECT 1
2022-03-18T07:16:21.933815350Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | FROM `nacos_config`.dual
2022-03-18T07:16:21.933820105Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: Object 'dual' not found within 'nacos_config'
2022-03-18T07:16:21.933824265Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.GeneratedConstructorAccessor30.newInstance(Unknown Source)
2022-03-18T07:16:21.933828208Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2022-03-18T07:16:21.933832190Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2022-03-18T07:16:21.933835994Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
2022-03-18T07:16:21.933840006Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:886)
2022-03-18T07:16:21.933845292Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:871)
2022-03-18T07:16:21.933850124Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5004)
2022-03-18T07:16:21.933854245Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:134)
2022-03-18T07:16:21.933858527Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:184)
2022-03-18T07:16:21.933862620Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
2022-03-18T07:16:21.933866777Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1064)
2022-03-18T07:16:21.933870756Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1038)
2022-03-18T07:16:21.933874818Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3166)
2022-03-18T07:16:21.933880495Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3148)
2022-03-18T07:16:21.933885257Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3422)
2022-03-18T07:16:21.933889410Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
2022-03-18T07:16:21.933893513Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
2022-03-18T07:16:21.933897484Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1064)
2022-03-18T07:16:21.933901549Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1038)
2022-03-18T07:16:21.933908594Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
2022-03-18T07:16:21.933912657Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1013)
2022-03-18T07:16:21.933918038Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:721)
2022-03-18T07:16:21.933922893Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.getRelRoot(DrdsSqlCompiler.java:396)
2022-03-18T07:16:21.933926957Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.compileQuery(DrdsSqlCompiler.java:330)
2022-03-18T07:16:21.933931024Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:219)
2022-03-18T07:16:21.933935239Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:211)
2022-03-18T07:16:21.933939245Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.spm.MemPlanCache.add(MemPlanCache.java:182)
2022-03-18T07:16:21.933943073Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.spm.QueryPlanner.getAcceptedMycatRelList(QueryPlanner.java:69)
2022-03-18T07:16:21.933947054Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.spm.QueryPlanner.innerComputeMinCostCodeExecuterContext(QueryPlanner.java:28)
2022-03-18T07:16:21.933952361Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.DrdsRunnerHelper.getPlan(DrdsRunnerHelper.java:370)
2022-03-18T07:16:21.933957141Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.calcite.DrdsRunnerHelper.runOnDrds(DrdsRunnerHelper.java:358)
2022-03-18T07:16:21.933960955Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.sqlhandler.ShardingSQLHandler.onExecute(ShardingSQLHandler.java:58)
2022-03-18T07:16:21.933964989Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
2022-03-18T07:16:21.933969158Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:481)
2022-03-18T07:16:21.933973113Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
2022-03-18T07:16:21.933977008Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
2022-03-18T07:16:21.933981615Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
2022-03-18T07:16:21.933987059Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
2022-03-18T07:16:21.933991924Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.compose(Future.java:199)
2022-03-18T07:16:21.933995925Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.flatMap(Future.java:180)
2022-03-18T07:16:21.933999957Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:446)
2022-03-18T07:16:21.934003814Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:200)
2022-03-18T07:16:21.934007792Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:196)
2022-03-18T07:16:21.934011664Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
2022-03-18T07:16:21.934015682Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
2022-03-18T07:16:21.934024044Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
2022-03-18T07:16:21.934029013Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
2022-03-18T07:16:21.934032966Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
2022-03-18T07:16:21.934036939Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.compose(Future.java:199)
2022-03-18T07:16:21.934040783Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.vertx.core.Future.flatMap(Future.java:180)
2022-03-18T07:16:21.934044708Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:196)
2022-03-18T07:16:21.934048707Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:524)
2022-03-18T07:16:21.934052875Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:94)
2022-03-18T07:16:21.934058123Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
2022-03-18T07:16:21.934063238Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-03-18T07:16:21.934067420Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-03-18T07:16:21.934071517Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
2022-03-18T07:16:21.934075364Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'dual' not found within 'nacos_config'
2022-03-18T07:16:21.934079371Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
2022-03-18T07:16:21.934083356Z iot_iot-mycat.1.vrdi348rqpc9@node5    | jvm 1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by junwen12221** [comment]
请把nacos_config.dual 这个表配置成单表

**Comment by li975732169** [comment]
ncaos 没这个表

**Comment by junwen12221** [comment]
:SELECT ? AS ?
2022-03-18T07:16:21.933793928Z iot_iot-mycat.1.vrdi348rqpc9@node5 | jvm 1 | FROM nacos_config.dual sqlNode:SELECT ? AS ?
2022-03-18T07:16:21.933801185Z iot_iot-mycat.1.vrdi348rqpc9@node5 | jvm 1 | FROM nacos_config.dual

要看看为啥有 FROM nacos_config.dual这种sql
