### ISSUE TITLE
单库分表怎么配置?

### ISSUE THREAD

**Issue by tlff** [MyCATApache/Mycat2#654]
我现在有一个数据库里面一个表很大,想要按照时间每月分一个表然后之前的数据还要保留.我翻了文档里面schema部分,没太搞明白.而且在shardingTables里配置了那个大表,其他的表就没法访问了.麻烦各位大大解答一下,感谢感谢

**Comment by junwen12221** [comment]
其他表没法访问是因为它们没有配置

**Comment by tlff** [comment]
其他的表很多我要一个个配置吗,而且诶具体怎么配置我也不清楚.文档里实在看的糊涂.我现在的配置是这样的. 
我还遇到了id自增的问题(虽然我想按时间分但是不知道怎么配置只能先hash(id)) 无论如何感谢您的回答
```json
"shardingTables": {
		"t_test": {
			// "autoIncrement": false,
			"function": {
				"properties": {
					"dbNum": "1", //分库数量
					"tableNum": "3", //分表数量
					"tableMethod": "hash(id)", //分表分片函数
					"storeNum": 1, //实际存储节点数量
					"dbMethod": "hash(id)", //分库分片函数
					"mappingFormat": "prototype/db/t_test_${tableIndex}"
				}
			}
}
```

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/xg1shb 

2.如何怎么把已经存在的物理表加载到mycat中?
使用schema配置中的targetName,指向目标数据源或者集群,同时保证schema的名字与目标的库相同,即可自动加载该库已经存在的物理表



单表可以批量加载;
分片表默认要一个一个配置,也可以通过建表语句执行执行配置.
id自增用全局序列号解决.

**Comment by tlff** [comment]
经过您的帮助mycat已经能够跑起来了,但是我想让分表按照自然月每月增长一张,然后我根据文档写出第二个配置
但是第二个配置运行会报`mycat-3002`的错误,您能帮我看看是哪里出问题了吗
还有 "tableNames":"test_table_${index}" 这里面的${index} 也有问题,这里因为分表是根据月份增长的所有没有上线,我没找到应该怎么写


```
正常的配置
"test_table": {
    "createTableSQL": "//省略",
    "function": {
        "properties": {
            "dbNum": 1,
            "mappingFormat": "prototype/rain_${dbIndex}/test_table_${index}",
            "tableNum": 3,
            "tableMethod": "YYYYMM(time)",
            "storeNum": 1,
            "dbMethod": "YYYYMM(time)"
        },
        "ranges": {}
    },
    "partition": {},
    "shardingIndexTables": {}
}
```

```
有问题的
/*+ mycat:createTable{
	"schemaName":"test",
	"shardingTable":{
		"createTableSQL":"//省略",
		"function":{
			"clazz":"io.mycat.router.mycat1xfunction.PartitionByMonth",
			"properties":{
				"beginDate":"2020-01-01",
				"dateFormat":"yyyy-MM-dd",
				"columnName":"time"
			}
		},
		"partition":{
			"schemaNames":"test",
			"tableNames":"test_table_${index}",
			"targetNames":"prototype"
		}
	},
	"tableName":"test_table"
} */;
```
日志
```
INFO   | jvm 1    | 2022/03/30 08:47:18 | 2022-03-30 08:47:18,234[WARN]com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal:1494discard long time none received connection. , jdbcUrl : jdbc:mysql://mysql:3306/mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true, version : 1.2.5, lastPacketReceivedIdleMillis : 71521
INFO   | jvm 1    | 2022/03/30 08:47:18 | 2022-03-30 08:47:18,303[ERROR]io.mycat.MycatDataContext.setLastMessage:117
INFO   | jvm 1    | 2022/03/30 08:47:18 | io.mycat.MycatException: ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:131)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.config.ConfigPrepareExecuter.createMetaData(ConfigPrepareExecuter.java:168)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.config.ConfigPrepareExecuter.prepareRuntimeObject(ConfigPrepareExecuter.java:113)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.config.FileMetadataStorageManager.commitAndSyncDisk(FileMetadataStorageManager.java:271)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.config.FileMetadataStorageManager$1.commit(FileMetadataStorageManager.java:250)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:498)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.sqlhandler.dql.HintHandler.mycatDmlHandler(HintHandler.java:945)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.sqlhandler.dql.HintHandler.onExecute(HintHandler.java:585)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:443)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:164)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:411)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:181)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:177)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:177)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:574)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:136)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:33)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2022/03/30 08:47:18 | Caused by: java.lang.ClassNotFoundException: io.mycat.router.mycat2xfunction.PartitionByMonth
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.lang.Class.forName0(Native Method)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at java.lang.Class.forName(Class.java:264)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.router.mycat1xfunction.PartitionRuleFunctionManager.createFunction(PartitionRuleFunctionManager.java:30)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.router.mycat1xfunction.PartitionRuleFunctionManager.getRuleAlgorithm(PartitionRuleFunctionManager.java:47)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.MetadataManager.createShardingTable(MetadataManager.java:543)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.MetadataManager.addShardingTable(MetadataManager.java:511)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.MetadataManager.<init>(MetadataManager.java:273)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:124)
INFO   | jvm 1    | 2022/03/30 08:47:18 | 	... 32 common frames omitted

```

**Comment by junwen12221** [comment]
```
/*+ mycat:createTable{
	"schemaName":"mysql",
	"shardingTable":{
		"createTableSQL":"xxx",
		"function":{
			"clazz":"io.mycat.router.mycat1xfunction.PartitionByMonth",
			"properties":{
				"beginDate":"2021-01-01 00:00:00",
				"endDate":"",
				"dateFormat":"yyyy-MM-dd hh:mm:ss",
				"columnName":"D_CREATE_TIME"
			},
			"ranges":{}
		},
		"partition":{
			"schemaNames":"db1",
			"tableNames":"t_2021$01-12",
			"targetNames":"prototype"
		},
		"shardingIndexTables":{}
	},
	"tableName":"cm_component_value"
} */;
```
