### ISSUE TITLE
建表后使用全局二级索引查询报错

### ISSUE THREAD

**Issue by theorix** [MyCATApache/Mycat2#668]
**Describe the bug**
建表后使用全局二级索引查询时报错。
（如果分表键由user_id改成id就不报错）
**To Reproduce**
1. 建表
```
CREATE TABLE `user_info_j`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `app_id` varchar(40) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `alias` varchar(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  GLOBAL INDEX `index_app_id`(`app_id`) COVERING(`user_id`,`id`)  USING BTREE DBPARTITION by mod_hash(`app_id`) TBPARTITION by mod_hash(`app_id`) DBPARTITIONS 2 TBPARTITIONS 8
)
DBPARTITION BY mod_hash(user_id) DBPARTITIONS 2
TBPARTITION BY mod_hash(user_id) TBPARTITIONS 8;
```
2. 查询
```
select * from user_info_j where app_id ='xxx';
```
3. 返回结果
```
ERROR:
java.lang.RuntimeException: Error while applying rule MycatViewIndexViewRule, args [rel#5898:MycatView.MYCAT2.[](relNode=LocalFilter#5900,distribution=[maxmax.user_info_j],conditions==($1, ?0))]
```
4. mycat日志
```
INFO   | jvm 1    | 2022/04/15 08:01:40 | 2022-04-15 08:01:39,989[ERROR]io.mycat.sqlhandler.ShardingSQLHandler.onExecute:61SELECT *
INFO   | jvm 1    | 2022/04/15 08:01:40 | FROM `maxmax`.user_info_j
INFO   | jvm 1    | 2022/04/15 08:01:40 | WHERE app_id = 'xxx'
INFO   | jvm 1    | 2022/04/15 08:01:40 | java.lang.RuntimeException: Error while applying rule MycatViewIndexViewRule, args [rel#5898:MycatView.MYCAT2.[](relNode=LocalFilter#5900,distribution=[maxmax.user_info_j],conditions==($1, ?0))]
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:256)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at org.apache.calcite.plan.volcano.IterativeRuleDriver.drive(IterativeRuleDriver.java:58)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:510)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.DrdsSqlCompiler.optimizeWithCBO(DrdsSqlCompiler.java:485)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.DrdsSqlCompiler.compileQuery(DrdsSqlCompiler.java:357)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:219)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:211)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.spm.MemPlanCache.add(MemPlanCache.java:182)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.spm.QueryPlanner.getAcceptedMycatRelList(QueryPlanner.java:69)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.spm.QueryPlanner.innerComputeMinCostCodeExecuterContext(QueryPlanner.java:28)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.DrdsRunnerHelper.getPlan(DrdsRunnerHelper.java:370)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.DrdsRunnerHelper.runOnDrds(DrdsRunnerHelper.java:358)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.sqlhandler.ShardingSQLHandler.onExecute(ShardingSQLHandler.java:58)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:481)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:446)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:200)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:196)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:196)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:524)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:94)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2022/04/15 08:01:40 | Caused by: java.lang.IllegalArgumentException: field [user_id] not found; input fields are: [alias, app_id, id]
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at org.apache.calcite.tools.RelBuilder.field(RelBuilder.java:415)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at org.apache.calcite.tools.RelBuilder.join(RelBuilder.java:2307)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.logical.MycatView.produceIndexViews(MycatView.java:250)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.logical.MycatView.produceIndexViews(MycatView.java:159)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at io.mycat.calcite.logical.MycatViewIndexViewRule.onMatch(MycatViewIndexViewRule.java:55)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:229)
INFO   | jvm 1    | 2022/04/15 08:01:40 | 	... 37 common frames omitted

```

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-15.jar

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-15.jar

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-15.jar

**Comment by theorix** [comment]
可以用了 👍👍👍

**Comment by junwen12221** [comment]
全局二级索引多用

explain select * from user_info_j where app_id ='xxx';

查看执行计划,确保不拉取大量数据
