### ISSUE TITLE
MyCAT2 发生死锁或连接数不够导致客户端异常退出后，出现连接泄漏

### ISSUE THREAD

**Issue by TeslaCN** [MyCATApache/Mycat2#671]
**Describe the bug**

Mycat2 v1.21-2022-2-18

**To Reproduce**
1. 配置 2 个 JDBC dataSource，每个最大 48 连接；
1. 使用 BenchmarkSQL 5.0 初始化数据；
1. 使用 BenchmarkSQL 5.0 连接 MyCAT2 发压，16 Terminals（16 客户端）（所有 SQL 都带分片键，不明白为什么 16 客户端要使用超过 48 数据库连接）；
1. 客户端卡死，最后因连接数不够报错，客户端进程退出；
1. 使用 MySQL cli 连接 MyCAT2，执行任何查询都卡死，然后报连接数不够。然而此时已经没有任何其他客户端连接 MyCAT2 了。

**Expected behavior**

**Screenshots**

Mycat2 日志：
```
2022-04-20 14:10:45,028[ERROR]io.mycat.commands.VertxMySQLDatasourcePoolImpl.tryFail:189tryFail
io.mycat.MycatException: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:159)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:110)
	at io.mycat.commands.JdbcDatasourcePoolImpl.getConnection(JdbcDatasourcePoolImpl.java:43)
	at io.mycat.commands.MycatMySQLManagerImpl.getConnection(MycatMySQLManagerImpl.java:109)
	at io.mycat.AsyncMycatDataContextImpl.getConnection(AsyncMycatDataContextImpl.java:66)
	at io.mycat.AsyncMycatDataContextImpl.lambda$getObservables$11(AsyncMycatDataContextImpl.java:94)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservablePublish.connect(ObservablePublish.java:80)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:87)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:41)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1749)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1419)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1399)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:140)
	... 19 common frames omitted
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.mycat.MycatException: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
	at io.mycat.AsyncMycatDataContextImpl.lambda$null$10(AsyncMycatDataContextImpl.java:127)
	at io.vertx.core.impl.future.FutureImpl$2.onFailure(FutureImpl.java:112)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:163)
	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
	at io.vertx.core.impl.future.FutureImpl.onFailure(FutureImpl.java:106)
	at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:23)
	at io.mycat.AsyncMycatDataContextImpl.lambda$getObservables$11(AsyncMycatDataContextImpl.java:126)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservablePublish.connect(ObservablePublish.java:80)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:87)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:41)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.mycat.MycatException: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:159)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:110)
	at io.mycat.commands.JdbcDatasourcePoolImpl.getConnection(JdbcDatasourcePoolImpl.java:43)
	at io.mycat.commands.MycatMySQLManagerImpl.getConnection(MycatMySQLManagerImpl.java:109)
	at io.mycat.AsyncMycatDataContextImpl.getConnection(AsyncMycatDataContextImpl.java:66)
	at io.mycat.AsyncMycatDataContextImpl.lambda$getObservables$11(AsyncMycatDataContextImpl.java:94)
	... 14 more
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1749)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1419)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1399)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:140)
	... 19 more
Exception in thread "RxComputationThreadPool-1" io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.mycat.MycatException: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
	at io.mycat.AsyncMycatDataContextImpl.lambda$null$10(AsyncMycatDataContextImpl.java:127)
	at io.vertx.core.impl.future.FutureImpl$2.onFailure(FutureImpl.java:112)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:163)
	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
	at io.vertx.core.impl.future.FutureImpl.onFailure(FutureImpl.java:106)
	at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:23)
	at io.mycat.AsyncMycatDataContextImpl.lambda$getObservables$11(AsyncMycatDataContextImpl.java:126)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservablePublish.connect(ObservablePublish.java:80)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:87)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:41)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.mycat.MycatException: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:159)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:110)
	at io.mycat.commands.JdbcDatasourcePoolImpl.getConnection(JdbcDatasourcePoolImpl.java:43)
	at io.mycat.commands.MycatMySQLManagerImpl.getConnection(MycatMySQLManagerImpl.java:109)
	at io.mycat.AsyncMycatDataContextImpl.getConnection(AsyncMycatDataContextImpl.java:66)
	at io.mycat.AsyncMycatDataContextImpl.lambda$getObservables$11(AsyncMycatDataContextImpl.java:94)
	... 14 more
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1749)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1419)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1399)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection(JdbcConnectionManager.java:140)
	... 19 more
```

客户端报错：
```
Term-00, Running Average tpmTOTAL: 8316.68    Current tpmTOTAL: 5052    Memory Usage: 87MB / 492MB          14:09:55,642 [Thread-1] ERROR  jTPCCTData : Unexpected SQLException in STOCK_LEVEL
14:09:55,643 [Thread-1] ERROR  jTPCCTData : com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
14:09:55,653 [Thread-1] FATAL  jTPCCTerminal : Unexpected SQLException on rollback: java.lang.NullPointerException
java.sql.SQLException: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 48, maxActive 48, creating 0
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
        at jTPCCTData.executeStockLevel(jTPCCTData.java:1379)
        at jTPCCTData.execute(jTPCCTData.java:107)
        at jTPCCTerminal.executeTransactions(jTPCCTerminal.java:182)
        at jTPCCTerminal.run(jTPCCTerminal.java:88)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.Exception: Unexpected SQLException on rollback: java.lang.NullPointerException
        at jTPCCTData.executeStockLevel(jTPCCTData.java:1405)
        at jTPCCTData.execute(jTPCCTData.java:107)
        at jTPCCTerminal.executeTransactions(jTPCCTerminal.java:182)
        at jTPCCTerminal.run(jTPCCTerminal.java:88)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

![image](https://user-images.githubusercontent.com/20503072/164162266-8493a987-aca5-4096-8c1a-6afc56b8b40b.png)

![image](https://user-images.githubusercontent.com/20503072/164163166-2bc1c051-96be-4d10-8025-e7f710acb903.png)

**Additional context**

**Comment by TeslaCN** [comment]
我发现只用 1 客户端发压也会出现连接不够的情况。
在客户端卡死之前 Mycat2 日志中大量出现错误：
```
path:/home/wuweijie/projects/Mycat2/mycat2/target/classes
2022-04-20 15:49:52,453[INFO]io.mycat.MycatCore.newMycatServer:214start VertxMycatServer
2022-04-20 15:49:53,212[INFO]com.alibaba.druid.pool.DruidDataSource.init:990{dataSource-1} inited
2022-04-20 15:49:55,780[INFO]io.mycat.config.MycatRouterConfigOps.recoveryXA:728readXARecoveryLog start
2022-04-20 15:49:55,783[INFO]com.alibaba.druid.pool.DruidDataSource.init:990{dataSource-2} inited
2022-04-20 15:49:55,803[INFO]com.alibaba.druid.pool.DruidDataSource.init:990{dataSource-3} inited
2022-04-20 15:49:55,870[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server 4ed9370c-5944-4fef-8166-a7712c041b85 started up.
2022-04-20 15:49:55,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server d8a921b2-85ad-48e4-a5e3-00723d466cce started up.
2022-04-20 15:49:55,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server 379b0d96-03ea-4acb-a22f-e4cc36b3bde2 started up.
2022-04-20 15:49:55,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server 21f964ca-5208-4081-99ce-a5c53bcf70ee started up.
2022-04-20 15:49:55,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server e35b562b-5b68-4f75-a5c9-83c4667c19f0 started up.
2022-04-20 15:49:55,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server fb63a2b7-813a-4046-b84c-5b56256dc240 started up.
2022-04-20 15:49:55,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server fab44b7e-449c-4f57-a9b2-af694e8d4901 started up.
2022-04-20 15:49:55,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:120Mycat Vertx server a54295ec-f386-471e-ba3d-10d2c468dd6b started up.
2022-04-20 15:50:03,559[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:03,973[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:04,912[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:05,174[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:05,338[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:06,675[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:07,362[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:07,978[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:09,532[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:10,011[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:10,438[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:10,566[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:10,652[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:10,883[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:10,958[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:11,595[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:11,612[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:11,628[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:11,702[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:11,726[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:11,750[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:12,074[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:12,275[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:13,312[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:13,842[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:14,006[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:14,673[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:14,691[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:15,471[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:15,899[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:15,983[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,004[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,169[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,535[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,591[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,654[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,859[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,876[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:16,896[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:18,721[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:19,274[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:19,573[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:19,857[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:19,877[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:19,970[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:20,360[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:20,410[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
2022-04-20 15:50:21,669[ERROR]cn.mycat.vertx.xa.impl.LocalXaSqlConnection.lambda$rollback$9:124
```

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-20.jar

或者3-14号后的mycat2

这边也会计划用 BenchmarkSQL 5.0测试

**Comment by junwen12221** [comment]
更改xxx.user.json把事务改成proxy看看有没有这个问题.

**Comment by TeslaCN** [comment]
> 更改xxx.user.json把事务改成proxy看看有没有这个问题.

改成 proxy 跑了几分钟没问题
