### ISSUE TITLE
使用全局二级索引的表，更新数据的SQL会报错

### ISSUE THREAD

**Issue by theorix** [MyCATApache/Mycat2#673]
**To Reproduce**
1. 创建表和插入数据
```
CREATE TABLE `roster_application`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `from_user_id` bigint(20) NOT NULL,
  `to_user_id` bigint(20) NOT NULL,
  `status` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  GLOBAL INDEX `from_user_id`(`to_user_id`) COVERING(`from_user_id`,id) USING BTREE DBPARTITION by mod_hash(`to_user_id`) TBPARTITION by mod_hash(`to_user_id`) DBPARTITIONS 2 TBPARTITIONS 2
)
DBPARTITION BY mod_hash(from_user_id) DBPARTITIONS 2
TBPARTITION BY mod_hash(from_user_id) TBPARTITIONS 2;

insert into roster_application (`id`,`from_user_id`,`to_user_id`,`status`) values('1','111','222','0');
```
2. 更新数据：
```
update roster_application set status=1  where id='1';
或 update roster_application set status=1  where id='1' and from_user_id='111' and to_user_id='222';
```
3. 会报错:
```
jvm 1    |  at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:524)
jvm 1    |  at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:94)
jvm 1    |  at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
jvm 1    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    |  at java.lang.Thread.run(Thread.java:748)
jvm 1    | 2022-04-20 10:43:13,948[WARN]io.mycat.calcite.MycatRexExecutor.reduce:64
jvm 1    | java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
jvm 1    |  at java.util.ArrayList.rangeCheck(ArrayList.java:657)
jvm 1    |  at java.util.ArrayList.get(ArrayList.java:433)
jvm 1    |  at io.mycat.calcite.MycatRexExecutor$1.visitDynamicParam(MycatRexExecutor.java:42)
jvm 1    |  at io.mycat.calcite.MycatRexExecutor$1.visitDynamicParam(MycatRexExecutor.java:37)
jvm 1    |  at org.apache.calcite.rex.RexDynamicParam.accept(RexDynamicParam.java:58)
jvm 1    |  at org.apache.calcite.rex.RexShuttle.visitList(RexShuttle.java:158)
jvm 1    |  at org.apache.calcite.rex.RexShuttle.visitCall(RexShuttle.java:110)
jvm 1    |  at org.apache.calcite.rex.RexShuttle.visitCall(RexShuttle.java:33)
jvm 1    |  at org.apache.calcite.rex.RexCall.accept(RexCall.java:174)
jvm 1    |  at io.mycat.calcite.MycatRexExecutor.reduce(MycatRexExecutor.java:53)
jvm 1    |  at io.mycat.AsyncMycatDataContextImpl.getSqlMap(AsyncMycatDataContextImpl.java:343)
jvm 1    |  at io.mycat.AsyncMycatDataContextImpl$SqlMycatDataContextImpl.lambda$getPartition$2(AsyncMycatDataContextImpl.java:259)
jvm 1    |  at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
jvm 1    |  at io.mycat.AsyncMycatDataContextImpl$SqlMycatDataContextImpl.getPartition(AsyncMycatDataContextImpl.java:259)
jvm 1    |  at io.mycat.AsyncMycatDataContextImpl$SqlMycatDataContextImpl.getObservableList(AsyncMycatDataContextImpl.java:235)
jvm 1    |  at io.mycat.AsyncMycatDataContextImpl.getObservable(AsyncMycatDataContextImpl.java:287)
jvm 1    |  at Baz.bindObservable(Unknown Source)
jvm 1    |  at io.mycat.calcite.PrepareExecutor.asObservableObjectArray(PrepareExecutor.java:120)
jvm 1    |  at io.mycat.calcite.PrepareExecutor.asRowBaseIterator(PrepareExecutor.java:129)
jvm 1    |  at io.mycat.executor.ExecutorProviderImpl.runAsObjectArray(ExecutorProviderImpl.java:93)
jvm 1    |  at io.mycat.vertx.VertxUpdateExecuter.explainUpdate(VertxUpdateExecuter.java:234)
jvm 1    |  at io.mycat.calcite.plan.ObservablePlanImplementorImpl.executeUpdate(ObservablePlanImplementorImpl.java:58)
jvm 1    |  at io.mycat.calcite.DrdsRunnerHelper.impl(DrdsRunnerHelper.java:347)
jvm 1    |  at io.mycat.sqlhandler.dml.UpdateSQLHandler.executeUpdate(UpdateSQLHandler.java:162)
jvm 1    |  at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:142)
jvm 1    |  at io.mycat.sqlhandler.dml.UpdateSQLHandler.onExecute(UpdateSQLHandler.java:51)
jvm 1    |  at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
jvm 1    |  at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:481)
jvm 1    |  at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
jvm 1    |  at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
jvm 1    |  at io.vertx.core.Future.compose(Future.java:199)
jvm 1    |  at io.vertx.core.Future.flatMap(Future.java:180)
jvm 1    |  at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:446)
jvm 1    |  at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:200)
jvm 1    |  at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:196)
jvm 1    |  at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
jvm 1    |  at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
jvm 1    |  at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
jvm 1    |  at io.vertx.core.Future.compose(Future.java:199)
jvm 1    |  at io.vertx.core.Future.flatMap(Future.java:180)
jvm 1    |  at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:196)
jvm 1    |  at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:524)
jvm 1    |  at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:94)
jvm 1    |  at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
jvm 1    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    |  at java.lang.Thread.run(Thread.java:748)
jvm 1    | 2022-04-20 10:43:13,950[ERROR]io.mycat.commands.MycatdbCommand.lambda$execute$7:492
jvm 1    | java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
jvm 1    |  at java.util.ArrayList.rangeCheck(ArrayList.java:657)
jvm 1    |  at java.util.ArrayList.get(ArrayList.java:433)
jvm 1    |  at io.mycat.calcite.executor.MycatPreparedStatementUtil.lambda$extractParams$0(MycatPreparedStatementUtil.java:334)
jvm 1    |  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
jvm 1    |  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
jvm 1    |  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
jvm 1    |  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
jvm 1    |  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
jvm 1    |  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
jvm 1    |  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
jvm 1    |  at io.mycat.calcite.executor.MycatPreparedStatementUtil.extractParams(MycatPreparedStatementUtil.java:334)
jvm 1    |  at io.mycat.AsyncMycatDataContextImpl.lambda$getObservables$13(AsyncMycatDataContextImpl.java:148)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
jvm 1    |  at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservablePublish.connect(ObservablePublish.java:80)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:87)
jvm 1    |  at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:136)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:98)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
jvm 1    |  at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:53)
jvm 1    |  at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:56)
jvm 1    |  at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
jvm 1    |  at io.reactivex.rxjava3.internal.operators.single.SingleTimeout.subscribeActual(SingleTimeout.java:55)
jvm 1    |  at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
```

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-20.jar

**Comment by theorix** [comment]
问题解决了 谢谢 👍👍👍
