### ISSUE TITLE
 on duplicate key update times = times + 1 报错UnsupportedOperationException， 这个是不支持吗

### ISSUE THREAD

**Issue by theorix** [MyCATApache/Mycat2#678]
**To Reproduce**
1. 建表
```
CREATE TABLE `group_member_kick_time`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `group_id` bigint(20) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `times` tinyint(4) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `index_group_member_kick_time_unique`(`group_id`, `user_id`) USING BTREE
)
DBPARTITION BY mod_hash(group_id) DBPARTITIONS 2
TBPARTITION BY mod_hash(group_id) TBPARTITIONS 2;
```
2. 插入数据
```
insert into group_member_kick_time (group_id, user_id, times) values  (1, 2, 1)  on duplicate key update times = times + 1;
```
报错信息：
```
jvm 1    | 2022-04-22 08:45:06,058[ERROR]io.mycat.commands.MycatdbCommand.lambda$execute$7:502
jvm 1    | java.lang.UnsupportedOperationException: unsupported times = times + ?
jvm 1    |  at io.mycat.vertx.VertxExecuter.lambda$explainInsert$14(VertxExecuter.java:472)
jvm 1    |  at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
jvm 1    |  at java.util.Collections$2.tryAdvance(Collections.java:4717)
jvm 1    |  at java.util.Collections$2.forEachRemaining(Collections.java:4725)
jvm 1    |  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
jvm 1    |  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
jvm 1    |  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
jvm 1    |  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
jvm 1    |  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
jvm 1    |  at io.mycat.vertx.VertxExecuter.explainInsert(VertxExecuter.java:526)
jvm 1    |  at io.mycat.calcite.plan.ObservablePlanImplementorImpl.executeInsert(ObservablePlanImplementorImpl.java:67)
jvm 1    |  at io.mycat.calcite.DrdsRunnerHelper.impl(DrdsRunnerHelper.java:349)
jvm 1    |  at io.mycat.sqlhandler.dml.UpdateSQLHandler.executeUpdate(UpdateSQLHandler.java:162)
jvm 1    |  at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:142)
jvm 1    |  at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
jvm 1    |  at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
jvm 1    |  at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:491)
jvm 1    |  at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
jvm 1    |  at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
jvm 1    |  at io.vertx.core.Future.compose(Future.java:199)
jvm 1    |  at io.vertx.core.Future.flatMap(Future.java:180)
jvm 1    |  at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:446)
jvm 1    |  at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:200)
jvm 1    |  at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:196)
jvm 1    |  at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
jvm 1    |  at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
jvm 1    |  at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
jvm 1    |  at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
jvm 1    |  at io.vertx.core.Future.compose(Future.java:199)
jvm 1    |  at io.vertx.core.Future.flatMap(Future.java:180)
jvm 1    |  at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:196)
jvm 1    |  at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:525)
jvm 1    |  at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:95)
```

**Comment by junwen12221** [comment]
可以支持,我这边先验证一下

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.22-release/mycat2-1.22-release-jar-with-dependencies-2022-4-22.jar

https://www.yuque.com/ccazhw/ml3nkf/a61adca02a884c644fcaffff5c54bec5

**Comment by theorix** [comment]
可以了 谢谢 👍👍
