### ISSUE TITLE
wrapper.log report  Table 'mysql.proc' doesn't exist using MySQL 8.0.28

### ISSUE THREAD

**Issue by flankblack** [MyCATApache/Mycat2#725]
wrapper.log report  Table 'mysql.proc' doesn't exist using MySQL 8.0.28

Here is the log:
STATUS | wrapper  | 2022/06/27 16:44:06 | TERM trapped.  Shutting down.
STATUS | wrapper  | 2022/06/27 16:44:07 | <-- Wrapper Stopped
STATUS | wrapper  | 2022/06/27 16:44:17 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2022/06/27 16:44:18 | Launching a JVM...
INFO   | jvm 1    | 2022/06/27 16:44:18 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2022/06/27 16:44:18 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2022/06/27 16:44:18 | 
INFO   | jvm 1    | 2022/06/27 16:44:19 | path:/home/app/mycat/./conf
INFO   | jvm 1    | 2022/06/27 16:44:19 | 2022-06-27 16:44:19,172[INFO]io.mycat.MycatCore.newMycatServer:218start VertxMycatServer
INFO   | jvm 1    | 2022/06/27 16:44:19 | 2022-06-27 16:44:19,736[INFO]com.alibaba.druid.pool.DruidDataSource.init:990{dataSource-1} inited
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,570[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server 30d99204-4238-4d8d-94e7-d3764355a762 started up.
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,570[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server 18519c32-fd86-458e-87a5-b78e71114246 started up.
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,570[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server ed1e643e-fbbb-4294-beb8-8e8f02e548ce started up.
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,571[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server 44962a8a-9861-4c2b-80cb-b2ef7bd7ac65 started up.
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,571[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server 92b013b0-0e87-462c-a544-f892ff55190f started up.
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,571[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server 7f4411fa-9882-49fa-b979-fa85cd237d93 started up.
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,572[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server 4d903a5a-6074-4554-8f8f-dd05f1391570 started up.
INFO   | jvm 1    | 2022/06/27 16:44:21 | 2022-06-27 16:44:21,574[INFO]io.mycat.vertx.VertxMycatServer.lambda$start$1:119Mycat Vertx server 4acd06e8-0514-4c7b-8641-92013393ea93 started up.
INFO   | jvm 1    | 2022/06/27 16:44:34 | 2022-06-27 16:44:34,942[INFO]io.mycat.vertx.VertxMycatServer.lambda$addSession$0:148session:io.mycat.mycatmysql.MycatVertxMysqlSession@504fae is closing
INFO   | jvm 1    | 2022/06/27 16:44:40 | 2022-06-27 16:44:40,837[ERROR]io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0:138
INFO   | jvm 1    | 2022/06/27 16:44:40 | java.sql.SQLSyntaxErrorException: Table 'mysql.proc' doesn't exist
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1202)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:296)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:99)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.mycat.newquery.NewMycatConnectionImpl.prepareQuery(NewMycatConnectionImpl.java:91)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$prepareQuery$1(ThreadMycatConnectionImplWrapper.java:48)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 	at java.base/java.lang.Thread.run(Thread.java:833)
INFO   | jvm 1    | 2022/06/27 16:44:40 | 2022-06-27 16:44:40,872[INFO]io.mycat.vertx.VertxMycatServer.lambda$addSession$0:148session:io.mycat.mycatmysql.MycatVertxMysqlSession@59d9e10 is closing
INFO   | jvm 1    | 2022/06/27 16:47:08 | 2022-06-27 16:47:08,573[ERROR]io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0:138
INFO   | jvm 1    | 2022/06/27 16:47:08 | java.sql.SQLSyntaxErrorException: Table 'mysql.proc' doesn't exist
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1202)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:296)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:99)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.mycat.newquery.NewMycatConnectionImpl.prepareQuery(NewMycatConnectionImpl.java:91)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$prepareQuery$1(ThreadMycatConnectionImplWrapper.java:48)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
INFO   | jvm 1    | 2022/06/27 16:47:08 | 	at java.base/java.lang.Thread.run(Thread.java:833)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 2022-06-27 16:50:23,489[ERROR]io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0:138
INFO   | jvm 1    | 2022/06/27 16:50:23 | java.sql.SQLSyntaxErrorException: Table 'mysql.proc' doesn't exist
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:121)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.mycat.newquery.NewMycatConnectionImpl.prepareQuery(NewMycatConnectionImpl.java:91)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$prepareQuery$1(ThreadMycatConnectionImplWrapper.java:48)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
INFO   | jvm 1    | 2022/06/27 16:50:23 | 	at java.base/java.lang.Thread.run(Thread.java:833)

MySQL version:
![1](https://user-images.githubusercontent.com/108310134/176061928-97ba3064-587d-48e0-a07a-69ffea962879.png)

JDK Version:
![2](https://user-images.githubusercontent.com/108310134/176061945-0cb91196-4f88-42fd-a3b9-8428567b421f.png)

CentOS Version:
![3](https://user-images.githubusercontent.com/108310134/176062189-0dd5f412-32f6-4e6f-84b1-a35def54adcb.png)

**Comment by junwen12221** [comment]
如果不影响使用,不需要理会这个报错 或者在mysql上建立这个表,mysql.proc也可以消除错误
