### ISSUE TITLE
MyCat1.22创建分表失败

### ISSUE THREAD

**Issue by Sa-UpWorld** [MyCATApache/Mycat2#728]
CREATE TABLE db1.`orders` (
	id bigint NOT NULL AUTO_INCREMENT,
	order_type varchar(100) DEFAULT NULL,
	traveldate date DEFAULT NULL,
	fee decimal(10,0) DEFAULT NULL,
	days int DEFAULT NULL,
	blob longblob,
	PRIMARY KEY (id),
	KEY `id` (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 dbpartition by mod_hash(id) tbpartition by mod_hash(id) tbpartitions 1 dbpartitions 2
> 3002 - ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
> 时间: 0.112s

**Comment by junwen12221** [comment]
贴日志

**Comment by strongduanmu** [comment]
Following is exception stack:

```
2022-07-12 13:07:54,458[ERROR]io.vertx.core.impl.future.FutureImpl.?:?tryFail
io.mycat.MycatException: ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
	at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:135)
	at io.mycat.config.MycatRouterConfigOps.getMetadataManager(MycatRouterConfigOps.java:687)
	at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:546)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.createTable(CreateTableSQLHandler.java:135)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.lambda$onExecute$5(CreateTableSQLHandler.java:72)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.onExecute(CreateTableSQLHandler.java:50)
	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
	at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:440)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:409)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:185)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:181)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:181)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:575)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:135)
	at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: can not get storeNum
	at io.mycat.router.function.AutoFunctionFactory.lambda$getTableFunction$2(AutoFunctionFactory.java:69)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.mycat.router.function.AutoFunctionFactory.getTableFunction(AutoFunctionFactory.java:69)
	at io.mycat.router.mycat1xfunction.PartitionRuleFunctionManager.getRuleAlgorithm(PartitionRuleFunctionManager.java:51)
	at io.mycat.MetadataManager.createShardingTable(MetadataManager.java:387)
	at io.mycat.MetadataManager.addShardingTable(MetadataManager.java:357)
	at io.mycat.MetadataManager.addSchema(MetadataManager.java:224)
	at io.mycat.MetadataManager.<init>(MetadataManager.java:149)
	at io.mycat.MysqlMetadataManager.<init>(MysqlMetadataManager.java:9)
	at io.mycat.MetadataManager$1.<init>(MetadataManager.java:130)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:130)
	... 37 common frames omitted
2022-07-12 13:07:54,459[ERROR]io.vertx.core.impl.future.FutureImpl.?:?tryFail
io.mycat.MycatException: ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
	at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:135)
	at io.mycat.config.MycatRouterConfigOps.getMetadataManager(MycatRouterConfigOps.java:687)
	at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:546)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.createTable(CreateTableSQLHandler.java:135)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.lambda$onExecute$5(CreateTableSQLHandler.java:72)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.onExecute(CreateTableSQLHandler.java:50)
	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
	at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:440)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:409)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:185)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:181)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:181)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:575)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:135)
	at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: can not get storeNum
	at io.mycat.router.function.AutoFunctionFactory.lambda$getTableFunction$2(AutoFunctionFactory.java:69)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.mycat.router.function.AutoFunctionFactory.getTableFunction(AutoFunctionFactory.java:69)
	at io.mycat.router.mycat1xfunction.PartitionRuleFunctionManager.getRuleAlgorithm(PartitionRuleFunctionManager.java:51)
	at io.mycat.MetadataManager.createShardingTable(MetadataManager.java:387)
	at io.mycat.MetadataManager.addShardingTable(MetadataManager.java:357)
	at io.mycat.MetadataManager.addSchema(MetadataManager.java:224)
	at io.mycat.MetadataManager.<init>(MetadataManager.java:149)
	at io.mycat.MysqlMetadataManager.<init>(MysqlMetadataManager.java:9)
	at io.mycat.MetadataManager$1.<init>(MetadataManager.java:130)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:130)
	... 37 common frames omitted
2022-07-12 13:07:54,459[ERROR]io.vertx.core.impl.future.FutureImpl.?:?tryFail
io.mycat.MycatException: ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
	at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:135)
	at io.mycat.config.MycatRouterConfigOps.getMetadataManager(MycatRouterConfigOps.java:687)
	at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:546)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.createTable(CreateTableSQLHandler.java:135)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.lambda$onExecute$5(CreateTableSQLHandler.java:72)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.onExecute(CreateTableSQLHandler.java:50)
	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
	at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:440)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:409)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:185)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:181)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:181)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:575)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:135)
	at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: can not get storeNum
	at io.mycat.router.function.AutoFunctionFactory.lambda$getTableFunction$2(AutoFunctionFactory.java:69)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.mycat.router.function.AutoFunctionFactory.getTableFunction(AutoFunctionFactory.java:69)
	at io.mycat.router.mycat1xfunction.PartitionRuleFunctionManager.getRuleAlgorithm(PartitionRuleFunctionManager.java:51)
	at io.mycat.MetadataManager.createShardingTable(MetadataManager.java:387)
	at io.mycat.MetadataManager.addShardingTable(MetadataManager.java:357)
	at io.mycat.MetadataManager.addSchema(MetadataManager.java:224)
	at io.mycat.MetadataManager.<init>(MetadataManager.java:149)
	at io.mycat.MysqlMetadataManager.<init>(MysqlMetadataManager.java:9)
	at io.mycat.MetadataManager$1.<init>(MetadataManager.java:130)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:130)
	... 37 common frames omitted
2022-07-12 13:07:54,459[ERROR]io.vertx.core.impl.future.FutureImpl.?:?tryFail
io.mycat.MycatException: ERROR-CODE: [MYCAT-3002][ERR_FETCH_METADATA] MetadataManager init fail
	at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:156)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:135)
	at io.mycat.config.MycatRouterConfigOps.getMetadataManager(MycatRouterConfigOps.java:687)
	at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:546)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.createTable(CreateTableSQLHandler.java:135)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.lambda$onExecute$5(CreateTableSQLHandler.java:72)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.onExecute(CreateTableSQLHandler.java:50)
	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:55)
	at io.mycat.commands.MycatdbCommand.lambda$execute$5(MycatdbCommand.java:440)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:409)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:185)
	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:181)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
	at io.vertx.core.Future.compose(Future.java:199)
	at io.vertx.core.Future.flatMap(Future.java:180)
	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:181)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:575)
	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:135)
	at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: can not get storeNum
	at io.mycat.router.function.AutoFunctionFactory.lambda$getTableFunction$2(AutoFunctionFactory.java:69)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.mycat.router.function.AutoFunctionFactory.getTableFunction(AutoFunctionFactory.java:69)
	at io.mycat.router.mycat1xfunction.PartitionRuleFunctionManager.getRuleAlgorithm(PartitionRuleFunctionManager.java:51)
	at io.mycat.MetadataManager.createShardingTable(MetadataManager.java:387)
	at io.mycat.MetadataManager.addShardingTable(MetadataManager.java:357)
	at io.mycat.MetadataManager.addSchema(MetadataManager.java:224)
	at io.mycat.MetadataManager.<init>(MetadataManager.java:149)
	at io.mycat.MysqlMetadataManager.<init>(MysqlMetadataManager.java:9)
	at io.mycat.MetadataManager$1.<init>(MetadataManager.java:130)
	at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:130)
	... 37 common frames omitted
2022-07-12 13:07:55,719[INFO]com.alibaba.druid.pool.DruidDataSource.close:2043{dataSource-1} closing ...
```
