### ISSUE TITLE
长SQL报错

### ISSUE THREAD

**Issue by HobartTimothy** [MyCATApache/Mycat2#732]
错误:
java.lang.Throwable: Packet for query is too large (800,262 > 666,666). You can change this value on the server by setting the 'max_allowed_packet' variable.
	at cn.stardust.easitline.core.dao.DaoContext.queryForList(DaoContext.java:273)
	at cn.stardust.yq.bpo.report.dao.ReportDao.inputAndOutputSummary(ReportDao.java:1872)
	at sun.reflect.GeneratedMethodAccessor848.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cn.stardust.easitline.core.web.EasyDaoBaseServlet.invokeMethod(EasyDaoBaseServlet.java:336)
	at cn.stardust.easitline.core.web.EasyDaoBaseServlet.doPost(EasyDaoBaseServlet.java:146)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:291)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

mysql配置是正确的：
![image](https://user-images.githubusercontent.com/24711993/179428841-6d5a1185-a596-45ef-a4a4-32019248ae72.png)

**Comment by zwyqz** [comment]
1019100252 联系我；

**Comment by zwyqz** [comment]
datasource配置文件裏面配置看看；
{

	"initSqls":["SET GLOBAL max_allowed_packet=150000000"],

}
