### ISSUE TITLE
Connection reset by peer  +   close statement error 异常定期出现

### ISSUE THREAD

**Issue by minxiangnan** [MyCATApache/Mycat2#750]
定期出现以下异常
2022-09-03 19:01:31,684[ERROR]io.vertx.core.net.impl.ConnectionBase.?:?Connection reset by peer
2022-09-03 19:10:00,774[ERROR]com.alibaba.druid.util.JdbcUtils.close:109close statement error
java.lang.NullPointerException: null
	at com.mysql.cj.jdbc.StatementImpl.closeAllOpenResults(StatementImpl.java:452)
	at com.mysql.cj.jdbc.StatementImpl.realClose(StatementImpl.java:1794)
	at com.mysql.cj.jdbc.StatementImpl.close(StatementImpl.java:426)
	at com.alibaba.druid.pool.DruidPooledStatement.close(DruidPooledStatement.java:504)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:98)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:323)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1916)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:340)
	at com.alibaba.druid.pool.DruidPooledConnection.syncClose(DruidPooledConnection.java:315)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:259)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:85)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.closeConnection(JdbcConnectionManager.java:206)
	at io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.closeConnection(JdbcConnectionManager.java:46)
	at io.mycat.datasource.jdbc.datasource.DefaultConnection.close(DefaultConnection.java:109)
	at io.mycat.commands.JdbcDatasourcePoolImpl$1.lambda$close$0(JdbcDatasourcePoolImpl.java:80)
	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
	at io.mycat.commands.JdbcDatasourcePoolImpl$1.close(JdbcDatasourcePoolImpl.java:77)
	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$close$6(ThreadMycatConnectionImplWrapper.java:150)
	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2022-09-03 20:44:21,682[ERROR]io.vertx.core.net.impl.ConnectionBase.?:?Connection reset by peer

应用连接池配置
  datasource:
    druid:
      url: jdbc:mysql://mycat-svc:8066/brain?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&connectTimeout=30000&socketTimeout=30000&rewriteBatchedStatements=true
      username: root
      password: 123456
      maxActive: 150
      initialSize: 25
      maxWait: 60000
      minIdle: 25
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

**Comment by minxiangnan** [comment]
v1.22-2022-6-25 版本

**Comment by dangnian** [comment]
解决了吗？
