### ISSUE TITLE
1.22版本全局表插入更新删除数据报错Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by 793834982** [MyCATApache/Mycat2#773]
1.22版本全局表插入更新删除数据报错Lock wait timeout exceeded; try restarting transaction
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1348)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
        at io.mycat.newquery.NewMycatConnectionImpl.lambda$update$6(NewMycatConnectionImpl.java:562)
        at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
        at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
        at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
        at io.mycat.newquery.NewMycatConnectionImpl.update(NewMycatConnectionImpl.java:541)
        at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$update$5(ThreadMycatConnectionImplWrapper.java:134)
        at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by 793834982** [comment]
已解决

**Comment by wyy-dev** [comment]
> 已解决

请问是怎么解决的，我这里也遇到这个问题了，插入数据很慢
